package main

import (
	"flag"
	"fmt"
	"os"
	"os/exec"
	"path/filepath"
	"strings"
)

// raglit as a systemd user service.
//
// The daemon was started by hand — `setsid nohup raglit daemon … &` from
// whatever shell happened to be open, reparented to init, logging to a file
// nobody tails. Nothing restarted it if it died and nothing started it at boot,
// so a reboot left every index unserved until a person noticed. raglit already
// knows how to shut itself down cleanly; what it lacked was anything to start it.
//
// This deliberately mirrors `corrallm service` on the same box: same verbs, same
// unit shape, so an operator learns one thing rather than two.

const serviceUnitName = "raglit"

func serviceUsage() {
	fmt.Fprint(os.Stderr, `raglit service — run the daemon under systemd (user)

  raglit service install [flags] [-- <daemon flags>...]
  raglit service uninstall
  raglit service start | stop | restart | status | logs

install flags:
  --name NAME     unit name without .service (default raglit)
  --exec PATH     raglit binary for the unit (default: this one, symlinks resolved)
  --env K=V       environment for the unit (repeatable)
  --enable        start at login
  --start         start it now

Everything after -- is passed to 'raglit daemon' verbatim and is validated
before the unit is written:

  raglit service install --enable --start -- -addr 127.0.0.1:7420,.76 -embed
`)
}

func runService(args []string) error {
	if len(args) == 0 {
		serviceUsage()
		os.Exit(2)
	}
	switch args[0] {
	case "install":
		return serviceInstall(args[1:])
	case "uninstall":
		return serviceUninstall(args[1:])
	case "start", "stop", "restart", "status":
		return serviceCtl(args[0], args[1:])
	case "logs":
		return serviceLogs(args[1:])
	default:
		serviceUsage()
		os.Exit(2)
		return nil
	}
}

func unitDir() (string, error) {
	home, err := os.UserHomeDir()
	if err != nil {
		return "", err
	}
	return filepath.Join(home, ".config", "systemd", "user"), nil
}

func systemctl(args ...string) *exec.Cmd {
	c := exec.Command("systemctl", append([]string{"--user"}, args...)...)
	c.Stdout, c.Stderr = os.Stdout, os.Stderr
	return c
}

// quoteUnit renders one argument for a systemd Exec line. systemd does its own
// unquoting, so an argument with a space silently becomes two, and a bare % is
// a specifier it would expand.
func quoteUnit(s string) string {
	if s != "" && !strings.ContainsAny(s, " \t\"'\\$%") {
		return s
	}
	r := strings.NewReplacer(`\`, `\\`, `"`, `\"`, `%`, `%%`)
	return `"` + r.Replace(s) + `"`
}

func renderUnit(execPath string, daemonArgs, envs []string) string {
	parts := []string{quoteUnit(execPath), "daemon"}
	for _, a := range daemonArgs {
		parts = append(parts, quoteUnit(a))
	}
	var b strings.Builder
	fmt.Fprint(&b, "# Generated by `raglit service install`. Edits are overwritten on reinstall.\n")
	fmt.Fprint(&b, "[Unit]\nDescription=raglit — document index, ingest pipeline and search daemon\nAfter=default.target\n\n")
	b.WriteString("[Service]\nType=simple\n")
	// Prove the flags parse before the daemon is asked to serve with them. Under
	// Restart=on-failure a bad flag is not one error, it is a crash loop.
	fmt.Fprintf(&b, "ExecStartPre=%s daemon -check %s\n", quoteUnit(execPath), strings.Join(parts[2:], " "))
	fmt.Fprintf(&b, "ExecStart=%s\n", strings.Join(parts, " "))
	for _, e := range envs {
		fmt.Fprintf(&b, "Environment=%s\n", e)
	}
	b.WriteString(`
# Ingest, OCR and embedding are memory-hungry and run helper processes. A child
# being OOM-killed must not take the daemon — and every index it serves — with it.
OOMPolicy=continue

# SIGTERM the daemon only and let it wind down its own workers; it already knows
# how (raglit daemon -stop drives the same path). Signalling the whole cgroup
# would kill helper processes out from under an in-flight job instead.
KillMode=mixed

# An ingest job can be mid-document. Give it room to finish rather than
# SIGKILLing a half-written index.
TimeoutStopSec=120

Restart=on-failure
RestartSec=2

[Install]
WantedBy=default.target
`)
	return b.String()
}

type repeatable []string

func (r *repeatable) String() string     { return strings.Join(*r, ",") }
func (r *repeatable) Set(v string) error { *r = append(*r, v); return nil }

func serviceInstall(args []string) error {
	fs := flag.NewFlagSet("service install", flag.ExitOnError)
	name := fs.String("name", serviceUnitName, "unit name without .service")
	execPath := fs.String("exec", "", "raglit binary for the unit")
	enable := fs.Bool("enable", false, "start at login")
	start := fs.Bool("start", false, "start it now")
	var envs repeatable
	fs.Var(&envs, "env", "environment as KEY=VALUE (repeatable)")
	fs.Parse(args)
	daemonArgs := fs.Args()

	// -stop and -restart act on the daemon recorded in daemon.json and, in the
	// case of -restart, relaunch it DETACHED. Baked into a unit that would mean
	// systemd supervising a process that deliberately replaces itself with one
	// systemd does not know about — two daemons, or none.
	for _, a := range daemonArgs {
		if t := strings.TrimLeft(a, "-"); t == "stop" || t == "restart" {
			return fmt.Errorf("-%s manages a detached daemon and must not be in a unit; use `raglit service %s`", t, t)
		}
	}

	if *execPath == "" {
		p, err := os.Executable()
		if err != nil {
			return fmt.Errorf("locate this binary (pass --exec): %w", err)
		}
		if r, err := filepath.EvalSymlinks(p); err == nil {
			p = r
		}
		*execPath = p
	}
	abs, err := filepath.Abs(*execPath)
	if err != nil {
		return err
	}
	*execPath = abs

	// Validate through the daemon's OWN flag set before writing anything.
	chk := exec.Command(*execPath, append([]string{"daemon", "-check"}, daemonArgs...)...)
	chk.Stderr = os.Stderr
	if err := chk.Run(); err != nil {
		return fmt.Errorf("those daemon flags do not parse — refusing to write a unit that would crash-loop")
	}

	dir, err := unitDir()
	if err != nil {
		return err
	}
	if err := os.MkdirAll(dir, 0o755); err != nil {
		return err
	}
	unit := *name + ".service"
	path := filepath.Join(dir, unit)
	if err := os.WriteFile(path, []byte(renderUnit(*execPath, daemonArgs, envs)), 0o644); err != nil {
		return err
	}
	fmt.Printf("wrote %s\n  exec   %s\n  daemon %s\n", path, *execPath, strings.Join(daemonArgs, " "))

	if err := systemctl("daemon-reload").Run(); err != nil {
		return fmt.Errorf("daemon-reload: %w", err)
	}
	if *enable {
		if err := systemctl("enable", unit).Run(); err != nil {
			return err
		}
		fmt.Println("enabled at login")
	}
	if *start {
		if err := systemctl("restart", unit).Run(); err != nil {
			return err
		}
		fmt.Println("started")
	}
	return nil
}

func serviceUninstall(args []string) error {
	fs := flag.NewFlagSet("service uninstall", flag.ExitOnError)
	name := fs.String("name", serviceUnitName, "unit name without .service")
	fs.Parse(args)

	unit := *name + ".service"
	_ = systemctl("stop", unit).Run()
	_ = systemctl("disable", unit).Run()
	dir, err := unitDir()
	if err != nil {
		return err
	}
	p := filepath.Join(dir, unit)
	if err := os.Remove(p); err != nil && !os.IsNotExist(err) {
		return err
	}
	_ = systemctl("daemon-reload").Run()
	fmt.Printf("removed %s\n", p)
	return nil
}

func serviceCtl(verb string, args []string) error {
	fs := flag.NewFlagSet("service "+verb, flag.ExitOnError)
	name := fs.String("name", serviceUnitName, "unit name without .service")
	fs.Parse(args)
	return systemctl(verb, *name+".service").Run()
}

func serviceLogs(args []string) error {
	fs := flag.NewFlagSet("service logs", flag.ExitOnError)
	name := fs.String("name", serviceUnitName, "unit name without .service")
	n := fs.String("n", "200", "lines to show")
	fs.Parse(args)
	c := exec.Command("journalctl", "--user", "-u", *name+".service", "-n", *n, "--no-pager")
	c.Stdout, c.Stderr = os.Stdout, os.Stderr
	return c.Run()
}
