// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: judgements_query.sql

package jdb

import (
	"context"
	"database/sql"
)

const appendJudgementLog = `-- name: AppendJudgementLog :exec
INSERT INTO judgement_log(kind, subject, payload, decided_by, decided_at, logged_at)
VALUES(?, ?, ?, ?, ?, ?)
`

type AppendJudgementLogParams struct {
	Kind      string `db:"kind" derived:"judgement_log.kind" json:"kind"`
	Subject   string `db:"subject" derived:"judgement_log.subject" json:"subject"`
	Payload   string `db:"payload" derived:"judgement_log.payload" json:"payload"`
	DecidedBy string `db:"decided_by" derived:"judgement_log.decided_by" json:"decided_by"`
	DecidedAt string `db:"decided_at" derived:"judgement_log.decided_at" json:"decided_at"`
	LoggedAt  int64  `db:"logged_at" derived:"judgement_log.logged_at" json:"logged_at"`
}

// ===== history =====
func (q *Queries) AppendJudgementLog(ctx context.Context, arg AppendJudgementLogParams) error {
	_, err := q.db.ExecContext(ctx, appendJudgementLog,
		arg.Kind,
		arg.Subject,
		arg.Payload,
		arg.DecidedBy,
		arg.DecidedAt,
		arg.LoggedAt,
	)
	return err
}

const countRelationsByKind = `-- name: CountRelationsByKind :many
SELECT kind, COUNT(*) AS n FROM doc_relations GROUP BY kind ORDER BY kind
`

type CountRelationsByKindRow struct {
	Kind string `db:"kind" derived:"doc_relations.kind" json:"kind"`
	N    int64  `db:"n" json:"n"`
}

func (q *Queries) CountRelationsByKind(ctx context.Context) ([]CountRelationsByKindRow, error) {
	rows, err := q.db.QueryContext(ctx, countRelationsByKind)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []CountRelationsByKindRow
	for rows.Next() {
		var i CountRelationsByKindRow
		if err := rows.Scan(&i.Kind, &i.N); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const deleteSlice = `-- name: DeleteSlice :exec
DELETE FROM doc_slices WHERE id = ?
`

func (q *Queries) DeleteSlice(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, deleteSlice, id)
	return err
}

const getRelation = `-- name: GetRelation :one
SELECT id, a, b, kind, supersedes, note, decided_by, decided_at, relation, coverage
FROM doc_relations WHERE a = ? AND b = ?
`

type GetRelationParams struct {
	A string `db:"a" derived:"doc_relations.a" json:"a"`
	B string `db:"b" derived:"doc_relations.b" json:"b"`
}

func (q *Queries) GetRelation(ctx context.Context, arg GetRelationParams) (DocRelation, error) {
	row := q.db.QueryRowContext(ctx, getRelation, arg.A, arg.B)
	var i DocRelation
	err := row.Scan(
		&i.ID,
		&i.A,
		&i.B,
		&i.Kind,
		&i.Supersedes,
		&i.Note,
		&i.DecidedBy,
		&i.DecidedAt,
		&i.Relation,
		&i.Coverage,
	)
	return i, err
}

const getSlice = `-- name: GetSlice :one
SELECT id, parent, from_page, to_page, title, note, decided_by, decided_at
FROM doc_slices WHERE id = ?
`

func (q *Queries) GetSlice(ctx context.Context, id string) (DocSlice, error) {
	row := q.db.QueryRowContext(ctx, getSlice, id)
	var i DocSlice
	err := row.Scan(
		&i.ID,
		&i.Parent,
		&i.FromPage,
		&i.ToPage,
		&i.Title,
		&i.Note,
		&i.DecidedBy,
		&i.DecidedAt,
	)
	return i, err
}

const listJudgementHistory = `-- name: ListJudgementHistory :many
SELECT id, kind, subject, payload, decided_by, decided_at, logged_at
FROM judgement_log WHERE kind = ? AND subject = ? ORDER BY id
`

type ListJudgementHistoryParams struct {
	Kind    string `db:"kind" derived:"judgement_log.kind" json:"kind"`
	Subject string `db:"subject" derived:"judgement_log.subject" json:"subject"`
}

func (q *Queries) ListJudgementHistory(ctx context.Context, arg ListJudgementHistoryParams) ([]JudgementLog, error) {
	rows, err := q.db.QueryContext(ctx, listJudgementHistory, arg.Kind, arg.Subject)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []JudgementLog
	for rows.Next() {
		var i JudgementLog
		if err := rows.Scan(
			&i.ID,
			&i.Kind,
			&i.Subject,
			&i.Payload,
			&i.DecidedBy,
			&i.DecidedAt,
			&i.LoggedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRelations = `-- name: ListRelations :many
SELECT id, a, b, kind, supersedes, note, decided_by, decided_at, relation, coverage
FROM doc_relations ORDER BY a, b
`

func (q *Queries) ListRelations(ctx context.Context) ([]DocRelation, error) {
	rows, err := q.db.QueryContext(ctx, listRelations)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []DocRelation
	for rows.Next() {
		var i DocRelation
		if err := rows.Scan(
			&i.ID,
			&i.A,
			&i.B,
			&i.Kind,
			&i.Supersedes,
			&i.Note,
			&i.DecidedBy,
			&i.DecidedAt,
			&i.Relation,
			&i.Coverage,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRelationsFor = `-- name: ListRelationsFor :many
SELECT id, a, b, kind, supersedes, note, decided_by, decided_at, relation, coverage
FROM doc_relations WHERE a = ? OR b = ? ORDER BY a, b
`

type ListRelationsForParams struct {
	A string `db:"a" derived:"doc_relations.a" json:"a"`
	B string `db:"b" derived:"doc_relations.b" json:"b"`
}

func (q *Queries) ListRelationsFor(ctx context.Context, arg ListRelationsForParams) ([]DocRelation, error) {
	rows, err := q.db.QueryContext(ctx, listRelationsFor, arg.A, arg.B)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []DocRelation
	for rows.Next() {
		var i DocRelation
		if err := rows.Scan(
			&i.ID,
			&i.A,
			&i.B,
			&i.Kind,
			&i.Supersedes,
			&i.Note,
			&i.DecidedBy,
			&i.DecidedAt,
			&i.Relation,
			&i.Coverage,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSliceParents = `-- name: ListSliceParents :many
SELECT DISTINCT parent FROM doc_slices ORDER BY parent
`

func (q *Queries) ListSliceParents(ctx context.Context) ([]string, error) {
	rows, err := q.db.QueryContext(ctx, listSliceParents)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var parent string
		if err := rows.Scan(&parent); err != nil {
			return nil, err
		}
		items = append(items, parent)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSlices = `-- name: ListSlices :many
SELECT id, parent, from_page, to_page, title, note, decided_by, decided_at
FROM doc_slices ORDER BY parent, from_page, to_page
`

func (q *Queries) ListSlices(ctx context.Context) ([]DocSlice, error) {
	rows, err := q.db.QueryContext(ctx, listSlices)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []DocSlice
	for rows.Next() {
		var i DocSlice
		if err := rows.Scan(
			&i.ID,
			&i.Parent,
			&i.FromPage,
			&i.ToPage,
			&i.Title,
			&i.Note,
			&i.DecidedBy,
			&i.DecidedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSlicesOf = `-- name: ListSlicesOf :many
SELECT id, parent, from_page, to_page, title, note, decided_by, decided_at
FROM doc_slices WHERE parent = ? ORDER BY from_page, to_page
`

func (q *Queries) ListSlicesOf(ctx context.Context, parent string) ([]DocSlice, error) {
	rows, err := q.db.QueryContext(ctx, listSlicesOf, parent)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []DocSlice
	for rows.Next() {
		var i DocSlice
		if err := rows.Scan(
			&i.ID,
			&i.Parent,
			&i.FromPage,
			&i.ToPage,
			&i.Title,
			&i.Note,
			&i.DecidedBy,
			&i.DecidedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertRelation = `-- name: UpsertRelation :exec

INSERT INTO doc_relations(a, b, kind, supersedes, note, decided_by, decided_at, relation, coverage)
VALUES(?, ?, ?, ?, ?, ?, ?, ?, ?)
ON CONFLICT(a, b) DO UPDATE SET
  kind=excluded.kind, supersedes=excluded.supersedes, note=excluded.note,
  decided_by=excluded.decided_by, decided_at=excluded.decided_at,
  relation=excluded.relation, coverage=excluded.coverage
`

type UpsertRelationParams struct {
	A          string         `db:"a" derived:"doc_relations.a" json:"a"`
	B          string         `db:"b" derived:"doc_relations.b" json:"b"`
	Kind       string         `db:"kind" derived:"doc_relations.kind" json:"kind"`
	Supersedes sql.NullString `db:"supersedes" derived:"doc_relations.supersedes" json:"supersedes"`
	Note       string         `db:"note" derived:"doc_relations.note" json:"note"`
	DecidedBy  string         `db:"decided_by" derived:"doc_relations.decided_by" json:"decided_by"`
	DecidedAt  string         `db:"decided_at" derived:"doc_relations.decided_at" json:"decided_at"`
	Relation   string         `db:"relation" derived:"doc_relations.relation" json:"relation"`
	Coverage   float64        `db:"coverage" derived:"doc_relations.coverage" json:"coverage"`
}

// Queries over the judgement database. See sql/judgements.sql for why it is a
// separate database from the index.
// ===== relations =====
func (q *Queries) UpsertRelation(ctx context.Context, arg UpsertRelationParams) error {
	_, err := q.db.ExecContext(ctx, upsertRelation,
		arg.A,
		arg.B,
		arg.Kind,
		arg.Supersedes,
		arg.Note,
		arg.DecidedBy,
		arg.DecidedAt,
		arg.Relation,
		arg.Coverage,
	)
	return err
}

const upsertSlice = `-- name: UpsertSlice :exec
INSERT INTO doc_slices(id, parent, from_page, to_page, title, note, decided_by, decided_at)
VALUES(?, ?, ?, ?, ?, ?, ?, ?)
ON CONFLICT(id) DO UPDATE SET
  parent=excluded.parent, from_page=excluded.from_page, to_page=excluded.to_page,
  title=excluded.title, note=excluded.note,
  decided_by=excluded.decided_by, decided_at=excluded.decided_at
`

type UpsertSliceParams struct {
	ID        string `db:"id" derived:"doc_slices.id" json:"id"`
	Parent    string `db:"parent" derived:"doc_slices.parent" json:"parent"`
	FromPage  int64  `db:"from_page" derived:"doc_slices.from_page" json:"from_page"`
	ToPage    int64  `db:"to_page" derived:"doc_slices.to_page" json:"to_page"`
	Title     string `db:"title" derived:"doc_slices.title" json:"title"`
	Note      string `db:"note" derived:"doc_slices.note" json:"note"`
	DecidedBy string `db:"decided_by" derived:"doc_slices.decided_by" json:"decided_by"`
	DecidedAt string `db:"decided_at" derived:"doc_slices.decided_at" json:"decided_at"`
}

// ===== slices =====
func (q *Queries) UpsertSlice(ctx context.Context, arg UpsertSliceParams) error {
	_, err := q.db.ExecContext(ctx, upsertSlice,
		arg.ID,
		arg.Parent,
		arg.FromPage,
		arg.ToPage,
		arg.Title,
		arg.Note,
		arg.DecidedBy,
		arg.DecidedAt,
	)
	return err
}
