// Code generated by sqlc-go-codegen-metaquery. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: judgements_query.sql

package jdb

import (
	"github.com/iodesystems/sqlc-go-codegen-metaquery/metaquery"
)

var _ = metaquery.Query{}

var MetaAppendJudgementLog = metaquery.Query{
	Name:    "AppendJudgementLog",
	Cmd:     ":exec",
	Source:  "judgements_query.sql",
	Dialect: metaquery.DialectSQLite,
	SQL: `INSERT INTO judgement_log(kind, subject, payload, decided_by, decided_at, logged_at)
VALUES(?, ?, ?, ?, ?, ?)`,
	Args: []metaquery.Arg{
		{Position: 1, Name: "kind", GoType: "string", DBType: "TEXT", NotNull: true},
		{Position: 2, Name: "subject", GoType: "string", DBType: "TEXT", NotNull: true},
		{Position: 3, Name: "payload", GoType: "string", DBType: "TEXT", NotNull: true},
		{Position: 4, Name: "decided_by", GoType: "string", DBType: "TEXT", NotNull: true},
		{Position: 5, Name: "decided_at", GoType: "string", DBType: "TEXT", NotNull: true},
		{Position: 6, Name: "logged_at", GoType: "int64", DBType: "INTEGER", NotNull: true},
	},
	Table: &metaquery.Table{Name: "judgement_log"},
}

// WrapAppendJudgementLog returns a metaquery.Builder over MetaAppendJudgementLog, pre-bound with typed arguments.
func WrapAppendJudgementLog(arg AppendJudgementLogParams) *metaquery.Builder {
	return metaquery.Wrap(&MetaAppendJudgementLog, arg.Kind, arg.Subject, arg.Payload, arg.DecidedBy, arg.DecidedAt, arg.LoggedAt)
}

var MetaCountRelationsByKind = metaquery.Query{
	Name:    "CountRelationsByKind",
	Cmd:     ":many",
	Source:  "judgements_query.sql",
	Dialect: metaquery.DialectSQLite,
	SQL:     `SELECT kind, COUNT(*) AS n FROM doc_relations GROUP BY kind ORDER BY kind`,
	Columns: []metaquery.Column{
		{Name: "kind", OriginalName: "kind", GoType: "string", DBType: "TEXT", NotNull: true, Table: "doc_relations"},
		{Name: "n", OriginalName: "n", GoType: "int64", DBType: "integer", NotNull: true},
	},
}

// WARNING: CountRelationsByKind ends in a top-level ORDER BY. Wrapping re-applies
// ordering at runtime, so .ApplyOrder(...) produces a doubled, nested sort
// that can defeat index use. Drop ORDER BY from the query and order via
// .ApplyOrder(...) instead. See benchmark/README.md.
// WrapCountRelationsByKind returns a metaquery.Builder over MetaCountRelationsByKind, pre-bound with typed arguments.
func WrapCountRelationsByKind() *metaquery.Builder {
	return metaquery.Wrap(&MetaCountRelationsByKind)
}

// CountRelationsByKindCols gives typed, name-safe access to CountRelationsByKind's output columns.
var CountRelationsByKindCols = struct {
	Kind metaquery.TextCol
	N    metaquery.IntCol
}{
	Kind: metaquery.NewTextCol("kind"),
	N:    metaquery.NewIntCol("n"),
}

var MetaDeletePageCorrection = metaquery.Query{
	Name:    "DeletePageCorrection",
	Cmd:     ":exec",
	Source:  "judgements_query.sql",
	Dialect: metaquery.DialectSQLite,
	SQL:     `DELETE FROM page_corrections WHERE doc = ? AND page = ?`,
	Args: []metaquery.Arg{
		{Position: 1, Name: "doc", GoType: "string", DBType: "TEXT", NotNull: true},
		{Position: 2, Name: "page", GoType: "int64", DBType: "INTEGER", NotNull: true},
	},
}

// WrapDeletePageCorrection returns a metaquery.Builder over MetaDeletePageCorrection, pre-bound with typed arguments.
func WrapDeletePageCorrection(arg DeletePageCorrectionParams) *metaquery.Builder {
	return metaquery.Wrap(&MetaDeletePageCorrection, arg.Doc, arg.Page)
}

var MetaDeleteSlice = metaquery.Query{
	Name:    "DeleteSlice",
	Cmd:     ":exec",
	Source:  "judgements_query.sql",
	Dialect: metaquery.DialectSQLite,
	SQL:     `DELETE FROM doc_slices WHERE id = ?`,
	Args: []metaquery.Arg{
		{Position: 1, Name: "id", GoType: "string", DBType: "TEXT", NotNull: true},
	},
}

// WrapDeleteSlice returns a metaquery.Builder over MetaDeleteSlice, pre-bound with typed arguments.
func WrapDeleteSlice(id string) *metaquery.Builder {
	return metaquery.Wrap(&MetaDeleteSlice, id)
}

var MetaGetRelation = metaquery.Query{
	Name:    "GetRelation",
	Cmd:     ":one",
	Source:  "judgements_query.sql",
	Dialect: metaquery.DialectSQLite,
	SQL: `SELECT id, a, b, kind, supersedes, note, decided_by, decided_at, relation, coverage
FROM doc_relations WHERE a = ? AND b = ?`,
	Columns: []metaquery.Column{
		{Name: "id", OriginalName: "id", GoType: "int64", DBType: "INTEGER", NotNull: true, Table: "doc_relations"},
		{Name: "a", OriginalName: "a", GoType: "string", DBType: "TEXT", NotNull: true, Table: "doc_relations"},
		{Name: "b", OriginalName: "b", GoType: "string", DBType: "TEXT", NotNull: true, Table: "doc_relations"},
		{Name: "kind", OriginalName: "kind", GoType: "string", DBType: "TEXT", NotNull: true, Table: "doc_relations"},
		{Name: "supersedes", OriginalName: "supersedes", GoType: "sql.NullString", DBType: "TEXT", Table: "doc_relations"},
		{Name: "note", OriginalName: "note", GoType: "string", DBType: "TEXT", NotNull: true, Table: "doc_relations"},
		{Name: "decided_by", OriginalName: "decided_by", GoType: "string", DBType: "TEXT", NotNull: true, Table: "doc_relations"},
		{Name: "decided_at", OriginalName: "decided_at", GoType: "string", DBType: "TEXT", NotNull: true, Table: "doc_relations"},
		{Name: "relation", OriginalName: "relation", GoType: "string", DBType: "TEXT", NotNull: true, Table: "doc_relations"},
		{Name: "coverage", OriginalName: "coverage", GoType: "float64", DBType: "REAL", NotNull: true, Table: "doc_relations"},
	},
	Args: []metaquery.Arg{
		{Position: 1, Name: "a", GoType: "string", DBType: "TEXT", NotNull: true},
		{Position: 2, Name: "b", GoType: "string", DBType: "TEXT", NotNull: true},
	},
}

// WrapGetRelation returns a metaquery.Builder over MetaGetRelation, pre-bound with typed arguments.
func WrapGetRelation(arg GetRelationParams) *metaquery.Builder {
	return metaquery.Wrap(&MetaGetRelation, arg.A, arg.B)
}

// GetRelationCols gives typed, name-safe access to GetRelation's output columns.
var GetRelationCols = struct {
	ID         metaquery.IntCol
	A          metaquery.TextCol
	B          metaquery.TextCol
	Kind       metaquery.TextCol
	Supersedes metaquery.AnyCol
	Note       metaquery.TextCol
	DecidedBy  metaquery.TextCol
	DecidedAt  metaquery.TextCol
	Relation   metaquery.TextCol
	Coverage   metaquery.FloatCol
}{
	ID:         metaquery.NewIntCol("id"),
	A:          metaquery.NewTextCol("a"),
	B:          metaquery.NewTextCol("b"),
	Kind:       metaquery.NewTextCol("kind"),
	Supersedes: metaquery.NewAnyCol("supersedes"),
	Note:       metaquery.NewTextCol("note"),
	DecidedBy:  metaquery.NewTextCol("decided_by"),
	DecidedAt:  metaquery.NewTextCol("decided_at"),
	Relation:   metaquery.NewTextCol("relation"),
	Coverage:   metaquery.NewFloatCol("coverage"),
}

var MetaGetSlice = metaquery.Query{
	Name:    "GetSlice",
	Cmd:     ":one",
	Source:  "judgements_query.sql",
	Dialect: metaquery.DialectSQLite,
	SQL: `SELECT id, parent, from_page, to_page, title, note, decided_by, decided_at
FROM doc_slices WHERE id = ?`,
	Columns: []metaquery.Column{
		{Name: "id", OriginalName: "id", GoType: "string", DBType: "TEXT", NotNull: true, Table: "doc_slices"},
		{Name: "parent", OriginalName: "parent", GoType: "string", DBType: "TEXT", NotNull: true, Table: "doc_slices"},
		{Name: "from_page", OriginalName: "from_page", GoType: "int64", DBType: "INTEGER", NotNull: true, Table: "doc_slices"},
		{Name: "to_page", OriginalName: "to_page", GoType: "int64", DBType: "INTEGER", NotNull: true, Table: "doc_slices"},
		{Name: "title", OriginalName: "title", GoType: "string", DBType: "TEXT", NotNull: true, Table: "doc_slices"},
		{Name: "note", OriginalName: "note", GoType: "string", DBType: "TEXT", NotNull: true, Table: "doc_slices"},
		{Name: "decided_by", OriginalName: "decided_by", GoType: "string", DBType: "TEXT", NotNull: true, Table: "doc_slices"},
		{Name: "decided_at", OriginalName: "decided_at", GoType: "string", DBType: "TEXT", NotNull: true, Table: "doc_slices"},
	},
	Args: []metaquery.Arg{
		{Position: 1, Name: "id", GoType: "string", DBType: "TEXT", NotNull: true},
	},
}

// WrapGetSlice returns a metaquery.Builder over MetaGetSlice, pre-bound with typed arguments.
func WrapGetSlice(id string) *metaquery.Builder {
	return metaquery.Wrap(&MetaGetSlice, id)
}

// GetSliceCols gives typed, name-safe access to GetSlice's output columns.
var GetSliceCols = struct {
	ID        metaquery.TextCol
	Parent    metaquery.TextCol
	FromPage  metaquery.IntCol
	ToPage    metaquery.IntCol
	Title     metaquery.TextCol
	Note      metaquery.TextCol
	DecidedBy metaquery.TextCol
	DecidedAt metaquery.TextCol
}{
	ID:        metaquery.NewTextCol("id"),
	Parent:    metaquery.NewTextCol("parent"),
	FromPage:  metaquery.NewIntCol("from_page"),
	ToPage:    metaquery.NewIntCol("to_page"),
	Title:     metaquery.NewTextCol("title"),
	Note:      metaquery.NewTextCol("note"),
	DecidedBy: metaquery.NewTextCol("decided_by"),
	DecidedAt: metaquery.NewTextCol("decided_at"),
}

var MetaListAllPageCorrections = metaquery.Query{
	Name:    "ListAllPageCorrections",
	Cmd:     ":many",
	Source:  "judgements_query.sql",
	Dialect: metaquery.DialectSQLite,
	SQL: `SELECT doc, page, text, note, corrected_by, corrected_at
FROM page_corrections ORDER BY doc, page`,
	Columns: []metaquery.Column{
		{Name: "doc", OriginalName: "doc", GoType: "string", DBType: "TEXT", NotNull: true, Table: "page_corrections"},
		{Name: "page", OriginalName: "page", GoType: "int64", DBType: "INTEGER", NotNull: true, Table: "page_corrections"},
		{Name: "text", OriginalName: "text", GoType: "string", DBType: "TEXT", NotNull: true, Table: "page_corrections"},
		{Name: "note", OriginalName: "note", GoType: "string", DBType: "TEXT", NotNull: true, Table: "page_corrections"},
		{Name: "corrected_by", OriginalName: "corrected_by", GoType: "string", DBType: "TEXT", NotNull: true, Table: "page_corrections"},
		{Name: "corrected_at", OriginalName: "corrected_at", GoType: "string", DBType: "TEXT", NotNull: true, Table: "page_corrections"},
	},
}

// WARNING: ListAllPageCorrections ends in a top-level ORDER BY. Wrapping re-applies
// ordering at runtime, so .ApplyOrder(...) produces a doubled, nested sort
// that can defeat index use. Drop ORDER BY from the query and order via
// .ApplyOrder(...) instead. See benchmark/README.md.
// WrapListAllPageCorrections returns a metaquery.Builder over MetaListAllPageCorrections, pre-bound with typed arguments.
func WrapListAllPageCorrections() *metaquery.Builder {
	return metaquery.Wrap(&MetaListAllPageCorrections)
}

// ListAllPageCorrectionsCols gives typed, name-safe access to ListAllPageCorrections's output columns.
var ListAllPageCorrectionsCols = struct {
	Doc         metaquery.TextCol
	Page        metaquery.IntCol
	Text        metaquery.TextCol
	Note        metaquery.TextCol
	CorrectedBy metaquery.TextCol
	CorrectedAt metaquery.TextCol
}{
	Doc:         metaquery.NewTextCol("doc"),
	Page:        metaquery.NewIntCol("page"),
	Text:        metaquery.NewTextCol("text"),
	Note:        metaquery.NewTextCol("note"),
	CorrectedBy: metaquery.NewTextCol("corrected_by"),
	CorrectedAt: metaquery.NewTextCol("corrected_at"),
}

var MetaListJudgementHistory = metaquery.Query{
	Name:    "ListJudgementHistory",
	Cmd:     ":many",
	Source:  "judgements_query.sql",
	Dialect: metaquery.DialectSQLite,
	SQL: `SELECT id, kind, subject, payload, decided_by, decided_at, logged_at
FROM judgement_log WHERE kind = ? AND subject = ? ORDER BY id`,
	Columns: []metaquery.Column{
		{Name: "id", OriginalName: "id", GoType: "int64", DBType: "INTEGER", NotNull: true, Table: "judgement_log"},
		{Name: "kind", OriginalName: "kind", GoType: "string", DBType: "TEXT", NotNull: true, Table: "judgement_log"},
		{Name: "subject", OriginalName: "subject", GoType: "string", DBType: "TEXT", NotNull: true, Table: "judgement_log"},
		{Name: "payload", OriginalName: "payload", GoType: "string", DBType: "TEXT", NotNull: true, Table: "judgement_log"},
		{Name: "decided_by", OriginalName: "decided_by", GoType: "string", DBType: "TEXT", NotNull: true, Table: "judgement_log"},
		{Name: "decided_at", OriginalName: "decided_at", GoType: "string", DBType: "TEXT", NotNull: true, Table: "judgement_log"},
		{Name: "logged_at", OriginalName: "logged_at", GoType: "int64", DBType: "INTEGER", NotNull: true, Table: "judgement_log"},
	},
	Args: []metaquery.Arg{
		{Position: 1, Name: "kind", GoType: "string", DBType: "TEXT", NotNull: true},
		{Position: 2, Name: "subject", GoType: "string", DBType: "TEXT", NotNull: true},
	},
}

// WARNING: ListJudgementHistory ends in a top-level ORDER BY. Wrapping re-applies
// ordering at runtime, so .ApplyOrder(...) produces a doubled, nested sort
// that can defeat index use. Drop ORDER BY from the query and order via
// .ApplyOrder(...) instead. See benchmark/README.md.
// WrapListJudgementHistory returns a metaquery.Builder over MetaListJudgementHistory, pre-bound with typed arguments.
func WrapListJudgementHistory(arg ListJudgementHistoryParams) *metaquery.Builder {
	return metaquery.Wrap(&MetaListJudgementHistory, arg.Kind, arg.Subject)
}

// ListJudgementHistoryCols gives typed, name-safe access to ListJudgementHistory's output columns.
var ListJudgementHistoryCols = struct {
	ID        metaquery.IntCol
	Kind      metaquery.TextCol
	Subject   metaquery.TextCol
	Payload   metaquery.TextCol
	DecidedBy metaquery.TextCol
	DecidedAt metaquery.TextCol
	LoggedAt  metaquery.IntCol
}{
	ID:        metaquery.NewIntCol("id"),
	Kind:      metaquery.NewTextCol("kind"),
	Subject:   metaquery.NewTextCol("subject"),
	Payload:   metaquery.NewTextCol("payload"),
	DecidedBy: metaquery.NewTextCol("decided_by"),
	DecidedAt: metaquery.NewTextCol("decided_at"),
	LoggedAt:  metaquery.NewIntCol("logged_at"),
}

var MetaListPageCorrections = metaquery.Query{
	Name:    "ListPageCorrections",
	Cmd:     ":many",
	Source:  "judgements_query.sql",
	Dialect: metaquery.DialectSQLite,
	SQL: `SELECT doc, page, text, note, corrected_by, corrected_at
FROM page_corrections WHERE doc = ? ORDER BY page`,
	Columns: []metaquery.Column{
		{Name: "doc", OriginalName: "doc", GoType: "string", DBType: "TEXT", NotNull: true, Table: "page_corrections"},
		{Name: "page", OriginalName: "page", GoType: "int64", DBType: "INTEGER", NotNull: true, Table: "page_corrections"},
		{Name: "text", OriginalName: "text", GoType: "string", DBType: "TEXT", NotNull: true, Table: "page_corrections"},
		{Name: "note", OriginalName: "note", GoType: "string", DBType: "TEXT", NotNull: true, Table: "page_corrections"},
		{Name: "corrected_by", OriginalName: "corrected_by", GoType: "string", DBType: "TEXT", NotNull: true, Table: "page_corrections"},
		{Name: "corrected_at", OriginalName: "corrected_at", GoType: "string", DBType: "TEXT", NotNull: true, Table: "page_corrections"},
	},
	Args: []metaquery.Arg{
		{Position: 1, Name: "doc", GoType: "string", DBType: "TEXT", NotNull: true},
	},
}

// WARNING: ListPageCorrections ends in a top-level ORDER BY. Wrapping re-applies
// ordering at runtime, so .ApplyOrder(...) produces a doubled, nested sort
// that can defeat index use. Drop ORDER BY from the query and order via
// .ApplyOrder(...) instead. See benchmark/README.md.
// WrapListPageCorrections returns a metaquery.Builder over MetaListPageCorrections, pre-bound with typed arguments.
func WrapListPageCorrections(doc string) *metaquery.Builder {
	return metaquery.Wrap(&MetaListPageCorrections, doc)
}

// ListPageCorrectionsCols gives typed, name-safe access to ListPageCorrections's output columns.
var ListPageCorrectionsCols = struct {
	Doc         metaquery.TextCol
	Page        metaquery.IntCol
	Text        metaquery.TextCol
	Note        metaquery.TextCol
	CorrectedBy metaquery.TextCol
	CorrectedAt metaquery.TextCol
}{
	Doc:         metaquery.NewTextCol("doc"),
	Page:        metaquery.NewIntCol("page"),
	Text:        metaquery.NewTextCol("text"),
	Note:        metaquery.NewTextCol("note"),
	CorrectedBy: metaquery.NewTextCol("corrected_by"),
	CorrectedAt: metaquery.NewTextCol("corrected_at"),
}

var MetaListRelations = metaquery.Query{
	Name:    "ListRelations",
	Cmd:     ":many",
	Source:  "judgements_query.sql",
	Dialect: metaquery.DialectSQLite,
	SQL: `SELECT id, a, b, kind, supersedes, note, decided_by, decided_at, relation, coverage
FROM doc_relations ORDER BY a, b`,
	Columns: []metaquery.Column{
		{Name: "id", OriginalName: "id", GoType: "int64", DBType: "INTEGER", NotNull: true, Table: "doc_relations"},
		{Name: "a", OriginalName: "a", GoType: "string", DBType: "TEXT", NotNull: true, Table: "doc_relations"},
		{Name: "b", OriginalName: "b", GoType: "string", DBType: "TEXT", NotNull: true, Table: "doc_relations"},
		{Name: "kind", OriginalName: "kind", GoType: "string", DBType: "TEXT", NotNull: true, Table: "doc_relations"},
		{Name: "supersedes", OriginalName: "supersedes", GoType: "sql.NullString", DBType: "TEXT", Table: "doc_relations"},
		{Name: "note", OriginalName: "note", GoType: "string", DBType: "TEXT", NotNull: true, Table: "doc_relations"},
		{Name: "decided_by", OriginalName: "decided_by", GoType: "string", DBType: "TEXT", NotNull: true, Table: "doc_relations"},
		{Name: "decided_at", OriginalName: "decided_at", GoType: "string", DBType: "TEXT", NotNull: true, Table: "doc_relations"},
		{Name: "relation", OriginalName: "relation", GoType: "string", DBType: "TEXT", NotNull: true, Table: "doc_relations"},
		{Name: "coverage", OriginalName: "coverage", GoType: "float64", DBType: "REAL", NotNull: true, Table: "doc_relations"},
	},
}

// WARNING: ListRelations ends in a top-level ORDER BY. Wrapping re-applies
// ordering at runtime, so .ApplyOrder(...) produces a doubled, nested sort
// that can defeat index use. Drop ORDER BY from the query and order via
// .ApplyOrder(...) instead. See benchmark/README.md.
// WrapListRelations returns a metaquery.Builder over MetaListRelations, pre-bound with typed arguments.
func WrapListRelations() *metaquery.Builder {
	return metaquery.Wrap(&MetaListRelations)
}

// ListRelationsCols gives typed, name-safe access to ListRelations's output columns.
var ListRelationsCols = struct {
	ID         metaquery.IntCol
	A          metaquery.TextCol
	B          metaquery.TextCol
	Kind       metaquery.TextCol
	Supersedes metaquery.AnyCol
	Note       metaquery.TextCol
	DecidedBy  metaquery.TextCol
	DecidedAt  metaquery.TextCol
	Relation   metaquery.TextCol
	Coverage   metaquery.FloatCol
}{
	ID:         metaquery.NewIntCol("id"),
	A:          metaquery.NewTextCol("a"),
	B:          metaquery.NewTextCol("b"),
	Kind:       metaquery.NewTextCol("kind"),
	Supersedes: metaquery.NewAnyCol("supersedes"),
	Note:       metaquery.NewTextCol("note"),
	DecidedBy:  metaquery.NewTextCol("decided_by"),
	DecidedAt:  metaquery.NewTextCol("decided_at"),
	Relation:   metaquery.NewTextCol("relation"),
	Coverage:   metaquery.NewFloatCol("coverage"),
}

var MetaListRelationsFor = metaquery.Query{
	Name:    "ListRelationsFor",
	Cmd:     ":many",
	Source:  "judgements_query.sql",
	Dialect: metaquery.DialectSQLite,
	SQL: `SELECT id, a, b, kind, supersedes, note, decided_by, decided_at, relation, coverage
FROM doc_relations WHERE a = ? OR b = ? ORDER BY a, b`,
	Columns: []metaquery.Column{
		{Name: "id", OriginalName: "id", GoType: "int64", DBType: "INTEGER", NotNull: true, Table: "doc_relations"},
		{Name: "a", OriginalName: "a", GoType: "string", DBType: "TEXT", NotNull: true, Table: "doc_relations"},
		{Name: "b", OriginalName: "b", GoType: "string", DBType: "TEXT", NotNull: true, Table: "doc_relations"},
		{Name: "kind", OriginalName: "kind", GoType: "string", DBType: "TEXT", NotNull: true, Table: "doc_relations"},
		{Name: "supersedes", OriginalName: "supersedes", GoType: "sql.NullString", DBType: "TEXT", Table: "doc_relations"},
		{Name: "note", OriginalName: "note", GoType: "string", DBType: "TEXT", NotNull: true, Table: "doc_relations"},
		{Name: "decided_by", OriginalName: "decided_by", GoType: "string", DBType: "TEXT", NotNull: true, Table: "doc_relations"},
		{Name: "decided_at", OriginalName: "decided_at", GoType: "string", DBType: "TEXT", NotNull: true, Table: "doc_relations"},
		{Name: "relation", OriginalName: "relation", GoType: "string", DBType: "TEXT", NotNull: true, Table: "doc_relations"},
		{Name: "coverage", OriginalName: "coverage", GoType: "float64", DBType: "REAL", NotNull: true, Table: "doc_relations"},
	},
	Args: []metaquery.Arg{
		{Position: 1, Name: "a", GoType: "string", DBType: "TEXT", NotNull: true},
		{Position: 2, Name: "b", GoType: "string", DBType: "TEXT", NotNull: true},
	},
}

// WARNING: ListRelationsFor ends in a top-level ORDER BY. Wrapping re-applies
// ordering at runtime, so .ApplyOrder(...) produces a doubled, nested sort
// that can defeat index use. Drop ORDER BY from the query and order via
// .ApplyOrder(...) instead. See benchmark/README.md.
// WrapListRelationsFor returns a metaquery.Builder over MetaListRelationsFor, pre-bound with typed arguments.
func WrapListRelationsFor(arg ListRelationsForParams) *metaquery.Builder {
	return metaquery.Wrap(&MetaListRelationsFor, arg.A, arg.B)
}

// ListRelationsForCols gives typed, name-safe access to ListRelationsFor's output columns.
var ListRelationsForCols = struct {
	ID         metaquery.IntCol
	A          metaquery.TextCol
	B          metaquery.TextCol
	Kind       metaquery.TextCol
	Supersedes metaquery.AnyCol
	Note       metaquery.TextCol
	DecidedBy  metaquery.TextCol
	DecidedAt  metaquery.TextCol
	Relation   metaquery.TextCol
	Coverage   metaquery.FloatCol
}{
	ID:         metaquery.NewIntCol("id"),
	A:          metaquery.NewTextCol("a"),
	B:          metaquery.NewTextCol("b"),
	Kind:       metaquery.NewTextCol("kind"),
	Supersedes: metaquery.NewAnyCol("supersedes"),
	Note:       metaquery.NewTextCol("note"),
	DecidedBy:  metaquery.NewTextCol("decided_by"),
	DecidedAt:  metaquery.NewTextCol("decided_at"),
	Relation:   metaquery.NewTextCol("relation"),
	Coverage:   metaquery.NewFloatCol("coverage"),
}

var MetaListSliceParents = metaquery.Query{
	Name:    "ListSliceParents",
	Cmd:     ":many",
	Source:  "judgements_query.sql",
	Dialect: metaquery.DialectSQLite,
	SQL:     `SELECT DISTINCT parent FROM doc_slices ORDER BY parent`,
	Columns: []metaquery.Column{
		{Name: "parent", OriginalName: "parent", GoType: "string"},
	},
}

// WARNING: ListSliceParents ends in a top-level ORDER BY. Wrapping re-applies
// ordering at runtime, so .ApplyOrder(...) produces a doubled, nested sort
// that can defeat index use. Drop ORDER BY from the query and order via
// .ApplyOrder(...) instead. See benchmark/README.md.
// WrapListSliceParents returns a metaquery.Builder over MetaListSliceParents, pre-bound with typed arguments.
func WrapListSliceParents() *metaquery.Builder {
	return metaquery.Wrap(&MetaListSliceParents)
}

// ListSliceParentsCols gives typed, name-safe access to ListSliceParents's output columns.
var ListSliceParentsCols = struct {
	Parent metaquery.TextCol
}{
	Parent: metaquery.NewTextCol("parent"),
}

var MetaListSlices = metaquery.Query{
	Name:    "ListSlices",
	Cmd:     ":many",
	Source:  "judgements_query.sql",
	Dialect: metaquery.DialectSQLite,
	SQL: `SELECT id, parent, from_page, to_page, title, note, decided_by, decided_at
FROM doc_slices ORDER BY parent, from_page, to_page`,
	Columns: []metaquery.Column{
		{Name: "id", OriginalName: "id", GoType: "string", DBType: "TEXT", NotNull: true, Table: "doc_slices"},
		{Name: "parent", OriginalName: "parent", GoType: "string", DBType: "TEXT", NotNull: true, Table: "doc_slices"},
		{Name: "from_page", OriginalName: "from_page", GoType: "int64", DBType: "INTEGER", NotNull: true, Table: "doc_slices"},
		{Name: "to_page", OriginalName: "to_page", GoType: "int64", DBType: "INTEGER", NotNull: true, Table: "doc_slices"},
		{Name: "title", OriginalName: "title", GoType: "string", DBType: "TEXT", NotNull: true, Table: "doc_slices"},
		{Name: "note", OriginalName: "note", GoType: "string", DBType: "TEXT", NotNull: true, Table: "doc_slices"},
		{Name: "decided_by", OriginalName: "decided_by", GoType: "string", DBType: "TEXT", NotNull: true, Table: "doc_slices"},
		{Name: "decided_at", OriginalName: "decided_at", GoType: "string", DBType: "TEXT", NotNull: true, Table: "doc_slices"},
	},
}

// WARNING: ListSlices ends in a top-level ORDER BY. Wrapping re-applies
// ordering at runtime, so .ApplyOrder(...) produces a doubled, nested sort
// that can defeat index use. Drop ORDER BY from the query and order via
// .ApplyOrder(...) instead. See benchmark/README.md.
// WrapListSlices returns a metaquery.Builder over MetaListSlices, pre-bound with typed arguments.
func WrapListSlices() *metaquery.Builder {
	return metaquery.Wrap(&MetaListSlices)
}

// ListSlicesCols gives typed, name-safe access to ListSlices's output columns.
var ListSlicesCols = struct {
	ID        metaquery.TextCol
	Parent    metaquery.TextCol
	FromPage  metaquery.IntCol
	ToPage    metaquery.IntCol
	Title     metaquery.TextCol
	Note      metaquery.TextCol
	DecidedBy metaquery.TextCol
	DecidedAt metaquery.TextCol
}{
	ID:        metaquery.NewTextCol("id"),
	Parent:    metaquery.NewTextCol("parent"),
	FromPage:  metaquery.NewIntCol("from_page"),
	ToPage:    metaquery.NewIntCol("to_page"),
	Title:     metaquery.NewTextCol("title"),
	Note:      metaquery.NewTextCol("note"),
	DecidedBy: metaquery.NewTextCol("decided_by"),
	DecidedAt: metaquery.NewTextCol("decided_at"),
}

var MetaListSlicesOf = metaquery.Query{
	Name:    "ListSlicesOf",
	Cmd:     ":many",
	Source:  "judgements_query.sql",
	Dialect: metaquery.DialectSQLite,
	SQL: `SELECT id, parent, from_page, to_page, title, note, decided_by, decided_at
FROM doc_slices WHERE parent = ? ORDER BY from_page, to_page`,
	Columns: []metaquery.Column{
		{Name: "id", OriginalName: "id", GoType: "string", DBType: "TEXT", NotNull: true, Table: "doc_slices"},
		{Name: "parent", OriginalName: "parent", GoType: "string", DBType: "TEXT", NotNull: true, Table: "doc_slices"},
		{Name: "from_page", OriginalName: "from_page", GoType: "int64", DBType: "INTEGER", NotNull: true, Table: "doc_slices"},
		{Name: "to_page", OriginalName: "to_page", GoType: "int64", DBType: "INTEGER", NotNull: true, Table: "doc_slices"},
		{Name: "title", OriginalName: "title", GoType: "string", DBType: "TEXT", NotNull: true, Table: "doc_slices"},
		{Name: "note", OriginalName: "note", GoType: "string", DBType: "TEXT", NotNull: true, Table: "doc_slices"},
		{Name: "decided_by", OriginalName: "decided_by", GoType: "string", DBType: "TEXT", NotNull: true, Table: "doc_slices"},
		{Name: "decided_at", OriginalName: "decided_at", GoType: "string", DBType: "TEXT", NotNull: true, Table: "doc_slices"},
	},
	Args: []metaquery.Arg{
		{Position: 1, Name: "parent", GoType: "string", DBType: "TEXT", NotNull: true},
	},
}

// WARNING: ListSlicesOf ends in a top-level ORDER BY. Wrapping re-applies
// ordering at runtime, so .ApplyOrder(...) produces a doubled, nested sort
// that can defeat index use. Drop ORDER BY from the query and order via
// .ApplyOrder(...) instead. See benchmark/README.md.
// WrapListSlicesOf returns a metaquery.Builder over MetaListSlicesOf, pre-bound with typed arguments.
func WrapListSlicesOf(parent string) *metaquery.Builder {
	return metaquery.Wrap(&MetaListSlicesOf, parent)
}

// ListSlicesOfCols gives typed, name-safe access to ListSlicesOf's output columns.
var ListSlicesOfCols = struct {
	ID        metaquery.TextCol
	Parent    metaquery.TextCol
	FromPage  metaquery.IntCol
	ToPage    metaquery.IntCol
	Title     metaquery.TextCol
	Note      metaquery.TextCol
	DecidedBy metaquery.TextCol
	DecidedAt metaquery.TextCol
}{
	ID:        metaquery.NewTextCol("id"),
	Parent:    metaquery.NewTextCol("parent"),
	FromPage:  metaquery.NewIntCol("from_page"),
	ToPage:    metaquery.NewIntCol("to_page"),
	Title:     metaquery.NewTextCol("title"),
	Note:      metaquery.NewTextCol("note"),
	DecidedBy: metaquery.NewTextCol("decided_by"),
	DecidedAt: metaquery.NewTextCol("decided_at"),
}

var MetaUpsertPageCorrection = metaquery.Query{
	Name:    "UpsertPageCorrection",
	Cmd:     ":exec",
	Source:  "judgements_query.sql",
	Dialect: metaquery.DialectSQLite,
	SQL: `INSERT INTO page_corrections(doc, page, text, note, corrected_by, corrected_at)
VALUES(?, ?, ?, ?, ?, ?)
ON CONFLICT(doc, page) DO UPDATE SET
  text=excluded.text, note=excluded.note,
  corrected_by=excluded.corrected_by, corrected_at=excluded.corrected_at`,
	Args: []metaquery.Arg{
		{Position: 1, Name: "doc", GoType: "string", DBType: "TEXT", NotNull: true},
		{Position: 2, Name: "page", GoType: "int64", DBType: "INTEGER", NotNull: true},
		{Position: 3, Name: "text", GoType: "string", DBType: "TEXT", NotNull: true},
		{Position: 4, Name: "note", GoType: "string", DBType: "TEXT", NotNull: true},
		{Position: 5, Name: "corrected_by", GoType: "string", DBType: "TEXT", NotNull: true},
		{Position: 6, Name: "corrected_at", GoType: "string", DBType: "TEXT", NotNull: true},
	},
	Table: &metaquery.Table{Name: "page_corrections"},
}

// WrapUpsertPageCorrection returns a metaquery.Builder over MetaUpsertPageCorrection, pre-bound with typed arguments.
func WrapUpsertPageCorrection(arg UpsertPageCorrectionParams) *metaquery.Builder {
	return metaquery.Wrap(&MetaUpsertPageCorrection, arg.Doc, arg.Page, arg.Text, arg.Note, arg.CorrectedBy, arg.CorrectedAt)
}

var MetaUpsertRelation = metaquery.Query{
	Name:    "UpsertRelation",
	Cmd:     ":exec",
	Source:  "judgements_query.sql",
	Dialect: metaquery.DialectSQLite,
	SQL: `
INSERT INTO doc_relations(a, b, kind, supersedes, note, decided_by, decided_at, relation, coverage)
VALUES(?, ?, ?, ?, ?, ?, ?, ?, ?)
ON CONFLICT(a, b) DO UPDATE SET
  kind=excluded.kind, supersedes=excluded.supersedes, note=excluded.note,
  decided_by=excluded.decided_by, decided_at=excluded.decided_at,
  relation=excluded.relation, coverage=excluded.coverage`,
	Args: []metaquery.Arg{
		{Position: 1, Name: "a", GoType: "string", DBType: "TEXT", NotNull: true},
		{Position: 2, Name: "b", GoType: "string", DBType: "TEXT", NotNull: true},
		{Position: 3, Name: "kind", GoType: "string", DBType: "TEXT", NotNull: true},
		{Position: 4, Name: "supersedes", GoType: "sql.NullString", DBType: "TEXT"},
		{Position: 5, Name: "note", GoType: "string", DBType: "TEXT", NotNull: true},
		{Position: 6, Name: "decided_by", GoType: "string", DBType: "TEXT", NotNull: true},
		{Position: 7, Name: "decided_at", GoType: "string", DBType: "TEXT", NotNull: true},
		{Position: 8, Name: "relation", GoType: "string", DBType: "TEXT", NotNull: true},
		{Position: 9, Name: "coverage", GoType: "float64", DBType: "REAL", NotNull: true},
	},
	Table: &metaquery.Table{Name: "doc_relations"},
}

// WrapUpsertRelation returns a metaquery.Builder over MetaUpsertRelation, pre-bound with typed arguments.
func WrapUpsertRelation(arg UpsertRelationParams) *metaquery.Builder {
	return metaquery.Wrap(&MetaUpsertRelation, arg.A, arg.B, arg.Kind, arg.Supersedes, arg.Note, arg.DecidedBy, arg.DecidedAt, arg.Relation, arg.Coverage)
}

var MetaUpsertSlice = metaquery.Query{
	Name:    "UpsertSlice",
	Cmd:     ":exec",
	Source:  "judgements_query.sql",
	Dialect: metaquery.DialectSQLite,
	SQL: `INSERT INTO doc_slices(id, parent, from_page, to_page, title, note, decided_by, decided_at)
VALUES(?, ?, ?, ?, ?, ?, ?, ?)
ON CONFLICT(id) DO UPDATE SET
  parent=excluded.parent, from_page=excluded.from_page, to_page=excluded.to_page,
  title=excluded.title, note=excluded.note,
  decided_by=excluded.decided_by, decided_at=excluded.decided_at`,
	Args: []metaquery.Arg{
		{Position: 1, Name: "id", GoType: "string", DBType: "TEXT", NotNull: true},
		{Position: 2, Name: "parent", GoType: "string", DBType: "TEXT", NotNull: true},
		{Position: 3, Name: "from_page", GoType: "int64", DBType: "INTEGER", NotNull: true},
		{Position: 4, Name: "to_page", GoType: "int64", DBType: "INTEGER", NotNull: true},
		{Position: 5, Name: "title", GoType: "string", DBType: "TEXT", NotNull: true},
		{Position: 6, Name: "note", GoType: "string", DBType: "TEXT", NotNull: true},
		{Position: 7, Name: "decided_by", GoType: "string", DBType: "TEXT", NotNull: true},
		{Position: 8, Name: "decided_at", GoType: "string", DBType: "TEXT", NotNull: true},
	},
	Table: &metaquery.Table{Name: "doc_slices"},
}

// WrapUpsertSlice returns a metaquery.Builder over MetaUpsertSlice, pre-bound with typed arguments.
func WrapUpsertSlice(arg UpsertSliceParams) *metaquery.Builder {
	return metaquery.Wrap(&MetaUpsertSlice, arg.ID, arg.Parent, arg.FromPage, arg.ToPage, arg.Title, arg.Note, arg.DecidedBy, arg.DecidedAt)
}
