// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package jdb

import (
	"database/sql"
)

type DocRelation struct {
	ID         int64          `db:"id" derived:"doc_relations.id" json:"id"`
	A          string         `db:"a" derived:"doc_relations.a" json:"a"`
	B          string         `db:"b" derived:"doc_relations.b" json:"b"`
	Kind       string         `db:"kind" derived:"doc_relations.kind" json:"kind"`
	Supersedes sql.NullString `db:"supersedes" derived:"doc_relations.supersedes" json:"supersedes"`
	Note       string         `db:"note" derived:"doc_relations.note" json:"note"`
	DecidedBy  string         `db:"decided_by" derived:"doc_relations.decided_by" json:"decided_by"`
	DecidedAt  string         `db:"decided_at" derived:"doc_relations.decided_at" json:"decided_at"`
	Relation   string         `db:"relation" derived:"doc_relations.relation" json:"relation"`
	Coverage   float64        `db:"coverage" derived:"doc_relations.coverage" json:"coverage"`
}

type DocSlice struct {
	ID        string `db:"id" derived:"doc_slices.id" json:"id"`
	Parent    string `db:"parent" derived:"doc_slices.parent" json:"parent"`
	FromPage  int64  `db:"from_page" derived:"doc_slices.from_page" json:"from_page"`
	ToPage    int64  `db:"to_page" derived:"doc_slices.to_page" json:"to_page"`
	Title     string `db:"title" derived:"doc_slices.title" json:"title"`
	Note      string `db:"note" derived:"doc_slices.note" json:"note"`
	DecidedBy string `db:"decided_by" derived:"doc_slices.decided_by" json:"decided_by"`
	DecidedAt string `db:"decided_at" derived:"doc_slices.decided_at" json:"decided_at"`
}

type JudgementLog struct {
	ID        int64  `db:"id" derived:"judgement_log.id" json:"id"`
	Kind      string `db:"kind" derived:"judgement_log.kind" json:"kind"`
	Subject   string `db:"subject" derived:"judgement_log.subject" json:"subject"`
	Payload   string `db:"payload" derived:"judgement_log.payload" json:"payload"`
	DecidedBy string `db:"decided_by" derived:"judgement_log.decided_by" json:"decided_by"`
	DecidedAt string `db:"decided_at" derived:"judgement_log.decided_at" json:"decided_at"`
	LoggedAt  int64  `db:"logged_at" derived:"judgement_log.logged_at" json:"logged_at"`
}
