// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

type Document struct {
	ID      int64  `db:"id" derived:"documents.id" json:"id"`
	Path    string `db:"path" derived:"documents.path" json:"path"`
	Title   string `db:"title" derived:"documents.title" json:"title"`
	AddedAt int64  `db:"added_at" derived:"documents.added_at" json:"added_at"`
}

type Fragment struct {
	ID    int64  `db:"id" derived:"fragments.id" json:"id"`
	DocID int64  `db:"doc_id" derived:"fragments.doc_id" json:"doc_id"`
	Page  int64  `db:"page" derived:"fragments.page" json:"page"`
	Ord   int64  `db:"ord" derived:"fragments.ord" json:"ord"`
	Text  string `db:"text" derived:"fragments.text" json:"text"`
}

type FragmentVector struct {
	FragmentID int64  `db:"fragment_id" derived:"fragment_vectors.fragment_id" json:"fragment_id"`
	Dim        int64  `db:"dim" derived:"fragment_vectors.dim" json:"dim"`
	Vec        []byte `db:"vec" derived:"fragment_vectors.vec" json:"vec"`
}

type FragmentsFt struct {
	Text string `db:"text" derived:"fragments_fts.text" json:"text"`
}

type IngestJob struct {
	ID         int64  `db:"id" derived:"ingest_jobs.id" json:"id"`
	Url        string `db:"url" derived:"ingest_jobs.url" json:"url"`
	Title      string `db:"title" derived:"ingest_jobs.title" json:"title"`
	State      string `db:"state" derived:"ingest_jobs.state" json:"state"`
	Error      string `db:"error" derived:"ingest_jobs.error" json:"error"`
	Fragments  int64  `db:"fragments" derived:"ingest_jobs.fragments" json:"fragments"`
	Mode       string `db:"mode" derived:"ingest_jobs.mode" json:"mode"`
	EnqueuedAt int64  `db:"enqueued_at" derived:"ingest_jobs.enqueued_at" json:"enqueued_at"`
	StartedAt  int64  `db:"started_at" derived:"ingest_jobs.started_at" json:"started_at"`
	FinishedAt int64  `db:"finished_at" derived:"ingest_jobs.finished_at" json:"finished_at"`
}

type JobStage struct {
	ID     int64  `db:"id" derived:"job_stages.id" json:"id"`
	JobID  int64  `db:"job_id" derived:"job_stages.job_id" json:"job_id"`
	Seq    int64  `db:"seq" derived:"job_stages.seq" json:"seq"`
	Name   string `db:"name" derived:"job_stages.name" json:"name"`
	Engine string `db:"engine" derived:"job_stages.engine" json:"engine"`
	State  string `db:"state" derived:"job_stages.state" json:"state"`
	Detail string `db:"detail" derived:"job_stages.detail" json:"detail"`
	At     int64  `db:"at" derived:"job_stages.at" json:"at"`
}

type OcrPage struct {
	DocID     int64  `db:"doc_id" derived:"ocr_pages.doc_id" json:"doc_id"`
	Page      int64  `db:"page" derived:"ocr_pages.page" json:"page"`
	Engine    string `db:"engine" derived:"ocr_pages.engine" json:"engine"`
	ImagePath string `db:"image_path" derived:"ocr_pages.image_path" json:"image_path"`
}

type Tombstone struct {
	Path string `db:"path" derived:"tombstones.path" json:"path"`
}
