// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"database/sql"
)

type Attestation struct {
	ID        int64  `db:"id" derived:"attestations.id" json:"id"`
	Doc       string `db:"doc" derived:"attestations.doc" json:"doc"`
	Seq       int64  `db:"seq" derived:"attestations.seq" json:"seq"`
	Unit      string `db:"unit" derived:"attestations.unit" json:"unit"`
	Kind      string `db:"kind" derived:"attestations.kind" json:"kind"`
	Blanket   int64  `db:"blanket" derived:"attestations.blanket" json:"blanket"`
	Text      string `db:"text" derived:"attestations.text" json:"text"`
	Label     string `db:"label" derived:"attestations.label" json:"label"`
	Note      string `db:"note" derived:"attestations.note" json:"note"`
	Statement string `db:"statement" derived:"attestations.statement" json:"statement"`
	Payload   string `db:"payload" derived:"attestations.payload" json:"payload"`
	RuledBy   string `db:"ruled_by" derived:"attestations.ruled_by" json:"ruled_by"`
	Auth      string `db:"auth" derived:"attestations.auth" json:"auth"`
	RuledAt   string `db:"ruled_at" derived:"attestations.ruled_at" json:"ruled_at"`
}

type Document struct {
	ID          int64  `db:"id" derived:"documents.id" json:"id"`
	Path        string `db:"path" derived:"documents.path" json:"path"`
	Title       string `db:"title" derived:"documents.title" json:"title"`
	AddedAt     int64  `db:"added_at" derived:"documents.added_at" json:"added_at"`
	ContentHash string `db:"content_hash" derived:"documents.content_hash" json:"content_hash"`
	FragMode    string `db:"frag_mode" derived:"documents.frag_mode" json:"frag_mode"`
	FragRecipe  string `db:"frag_recipe" derived:"documents.frag_recipe" json:"frag_recipe"`
	GenName     string `db:"gen_name" derived:"documents.gen_name" json:"gen_name"`
	GenSummary  string `db:"gen_summary" derived:"documents.gen_summary" json:"gen_summary"`
	GenKind     string `db:"gen_kind" derived:"documents.gen_kind" json:"gen_kind"`
	GenSource   string `db:"gen_source" derived:"documents.gen_source" json:"gen_source"`
	GenModel    string `db:"gen_model" derived:"documents.gen_model" json:"gen_model"`
	GenAt       int64  `db:"gen_at" derived:"documents.gen_at" json:"gen_at"`
	GenTextHash string `db:"gen_text_hash" derived:"documents.gen_text_hash" json:"gen_text_hash"`
}

type DocumentNote struct {
	ID        int64         `db:"id" derived:"document_notes.id" json:"id"`
	DocID     int64         `db:"doc_id" derived:"document_notes.doc_id" json:"doc_id"`
	Page      sql.NullInt64 `db:"page" derived:"document_notes.page" json:"page"`
	Body      string        `db:"body" derived:"document_notes.body" json:"body"`
	Author    string        `db:"author" derived:"document_notes.author" json:"author"`
	CreatedAt string        `db:"created_at" derived:"document_notes.created_at" json:"created_at"`
}

type Fragment struct {
	ID        int64  `db:"id" derived:"fragments.id" json:"id"`
	DocID     int64  `db:"doc_id" derived:"fragments.doc_id" json:"doc_id"`
	Page      int64  `db:"page" derived:"fragments.page" json:"page"`
	Ord       int64  `db:"ord" derived:"fragments.ord" json:"ord"`
	Text      string `db:"text" derived:"fragments.text" json:"text"`
	StartOff  int64  `db:"start_off" derived:"fragments.start_off" json:"start_off"`
	EndOff    int64  `db:"end_off" derived:"fragments.end_off" json:"end_off"`
	PageSpans string `db:"page_spans" derived:"fragments.page_spans" json:"page_spans"`
	Origin    string `db:"origin" derived:"fragments.origin" json:"origin"`
}

type FragmentVector struct {
	FragmentID int64  `db:"fragment_id" derived:"fragment_vectors.fragment_id" json:"fragment_id"`
	Dim        int64  `db:"dim" derived:"fragment_vectors.dim" json:"dim"`
	Vec        []byte `db:"vec" derived:"fragment_vectors.vec" json:"vec"`
}

type FragmentsFt struct {
	Text string `db:"text" derived:"fragments_fts.text" json:"text"`
}

type IdentityJob struct {
	ID         int64  `db:"id" derived:"identity_jobs.id" json:"id"`
	Path       string `db:"path" derived:"identity_jobs.path" json:"path"`
	State      string `db:"state" derived:"identity_jobs.state" json:"state"`
	Force      int64  `db:"force" derived:"identity_jobs.force" json:"force"`
	Error      string `db:"error" derived:"identity_jobs.error" json:"error"`
	EnqueuedAt int64  `db:"enqueued_at" derived:"identity_jobs.enqueued_at" json:"enqueued_at"`
	StartedAt  int64  `db:"started_at" derived:"identity_jobs.started_at" json:"started_at"`
	FinishedAt int64  `db:"finished_at" derived:"identity_jobs.finished_at" json:"finished_at"`
	OwnerPid   int64  `db:"owner_pid" derived:"identity_jobs.owner_pid" json:"owner_pid"`
}

type IndexMetum struct {
	Key       string `db:"key" derived:"index_meta.key" json:"key"`
	Value     string `db:"value" derived:"index_meta.value" json:"value"`
	UpdatedAt int64  `db:"updated_at" derived:"index_meta.updated_at" json:"updated_at"`
}

type IngestJob struct {
	ID         int64  `db:"id" derived:"ingest_jobs.id" json:"id"`
	Url        string `db:"url" derived:"ingest_jobs.url" json:"url"`
	Title      string `db:"title" derived:"ingest_jobs.title" json:"title"`
	State      string `db:"state" derived:"ingest_jobs.state" json:"state"`
	Error      string `db:"error" derived:"ingest_jobs.error" json:"error"`
	Fragments  int64  `db:"fragments" derived:"ingest_jobs.fragments" json:"fragments"`
	Mode       string `db:"mode" derived:"ingest_jobs.mode" json:"mode"`
	EnqueuedAt int64  `db:"enqueued_at" derived:"ingest_jobs.enqueued_at" json:"enqueued_at"`
	StartedAt  int64  `db:"started_at" derived:"ingest_jobs.started_at" json:"started_at"`
	FinishedAt int64  `db:"finished_at" derived:"ingest_jobs.finished_at" json:"finished_at"`
	OwnerPid   int64  `db:"owner_pid" derived:"ingest_jobs.owner_pid" json:"owner_pid"`
	Lane       string `db:"lane" derived:"ingest_jobs.lane" json:"lane"`
}

type JobStage struct {
	ID     int64  `db:"id" derived:"job_stages.id" json:"id"`
	JobID  int64  `db:"job_id" derived:"job_stages.job_id" json:"job_id"`
	Seq    int64  `db:"seq" derived:"job_stages.seq" json:"seq"`
	Name   string `db:"name" derived:"job_stages.name" json:"name"`
	Engine string `db:"engine" derived:"job_stages.engine" json:"engine"`
	State  string `db:"state" derived:"job_stages.state" json:"state"`
	Detail string `db:"detail" derived:"job_stages.detail" json:"detail"`
	At     int64  `db:"at" derived:"job_stages.at" json:"at"`
}

type MediaVector struct {
	MediaID int64  `db:"media_id" derived:"media_vectors.media_id" json:"media_id"`
	Dim     int64  `db:"dim" derived:"media_vectors.dim" json:"dim"`
	Vec     []byte `db:"vec" derived:"media_vectors.vec" json:"vec"`
	Space   string `db:"space" derived:"media_vectors.space" json:"space"`
}

type Medium struct {
	ID          int64         `db:"id" derived:"media.id" json:"id"`
	DocID       int64         `db:"doc_id" derived:"media.doc_id" json:"doc_id"`
	Page        int64         `db:"page" derived:"media.page" json:"page"`
	Ord         int64         `db:"ord" derived:"media.ord" json:"ord"`
	Kind        string        `db:"kind" derived:"media.kind" json:"kind"`
	ImagePath   string        `db:"image_path" derived:"media.image_path" json:"image_path"`
	Bbox        string        `db:"bbox" derived:"media.bbox" json:"bbox"`
	Description string        `db:"description" derived:"media.description" json:"description"`
	FragmentID  sql.NullInt64 `db:"fragment_id" derived:"media.fragment_id" json:"fragment_id"`
}

type OcrPage struct {
	DocID     int64  `db:"doc_id" derived:"ocr_pages.doc_id" json:"doc_id"`
	Page      int64  `db:"page" derived:"ocr_pages.page" json:"page"`
	Engine    string `db:"engine" derived:"ocr_pages.engine" json:"engine"`
	Model     string `db:"model" derived:"ocr_pages.model" json:"model"`
	Dpi       int64  `db:"dpi" derived:"ocr_pages.dpi" json:"dpi"`
	ImagePath string `db:"image_path" derived:"ocr_pages.image_path" json:"image_path"`
}

type OcrPageCache struct {
	ImgSha    string `db:"img_sha" derived:"ocr_page_cache.img_sha" json:"img_sha"`
	Engine    string `db:"engine" derived:"ocr_page_cache.engine" json:"engine"`
	Text      string `db:"text" derived:"ocr_page_cache.text" json:"text"`
	CreatedAt int64  `db:"created_at" derived:"ocr_page_cache.created_at" json:"created_at"`
}

type PageReading struct {
	ID     int64  `db:"id" derived:"page_readings.id" json:"id"`
	Doc    string `db:"doc" derived:"page_readings.doc" json:"doc"`
	Page   int64  `db:"page" derived:"page_readings.page" json:"page"`
	Seq    int64  `db:"seq" derived:"page_readings.seq" json:"seq"`
	Text   string `db:"text" derived:"page_readings.text" json:"text"`
	Source string `db:"source" derived:"page_readings.source" json:"source"`
	Engine string `db:"engine" derived:"page_readings.engine" json:"engine"`
	Model  string `db:"model" derived:"page_readings.model" json:"model"`
	Note   string `db:"note" derived:"page_readings.note" json:"note"`
	ReadBy string `db:"read_by" derived:"page_readings.read_by" json:"read_by"`
	ReadAt string `db:"read_at" derived:"page_readings.read_at" json:"read_at"`
	Active int64  `db:"active" derived:"page_readings.active" json:"active"`
}

type Reading struct {
	ID           int64  `db:"id" derived:"readings.id" json:"id"`
	SourceSha256 string `db:"source_sha256" derived:"readings.source_sha256" json:"source_sha256"`
	SourcePath   string `db:"source_path" derived:"readings.source_path" json:"source_path"`
	DocPath      string `db:"doc_path" derived:"readings.doc_path" json:"doc_path"`
	Method       string `db:"method" derived:"readings.method" json:"method"`
	Level        string `db:"level" derived:"readings.level" json:"level"`
	ProducedBy   string `db:"produced_by" derived:"readings.produced_by" json:"produced_by"`
	RuledBy      string `db:"ruled_by" derived:"readings.ruled_by" json:"ruled_by"`
	At           int64  `db:"at" derived:"readings.at" json:"at"`
	Text         string `db:"text" derived:"readings.text" json:"text"`
	Data         string `db:"data" derived:"readings.data" json:"data"`
	Ruled        string `db:"ruled" derived:"readings.ruled" json:"ruled"`
	Describes    int64  `db:"describes" derived:"readings.describes" json:"describes"`
}

type ShingleIndex struct {
	Hash  int64 `db:"hash" derived:"shingle_index.hash" json:"hash"`
	DocID int64 `db:"doc_id" derived:"shingle_index.doc_id" json:"doc_id"`
	Page  int64 `db:"page" derived:"shingle_index.page" json:"page"`
}

type ShinglePage struct {
	DocID   int64  `db:"doc_id" derived:"shingle_pages.doc_id" json:"doc_id"`
	Page    int64  `db:"page" derived:"shingle_pages.page" json:"page"`
	Chars   int64  `db:"chars" derived:"shingle_pages.chars" json:"chars"`
	Total   int64  `db:"total" derived:"shingle_pages.total" json:"total"`
	Sampled int64  `db:"sampled" derived:"shingle_pages.sampled" json:"sampled"`
	Recipe  string `db:"recipe" derived:"shingle_pages.recipe" json:"recipe"`
}

type Tombstone struct {
	Path string `db:"path" derived:"tombstones.path" json:"path"`
}

type Withdrawal struct {
	Path   string `db:"path" derived:"withdrawals.path" json:"path"`
	Reason string `db:"reason" derived:"withdrawals.reason" json:"reason"`
	ByWho  string `db:"by_who" derived:"withdrawals.by_who" json:"by_who"`
	At     string `db:"at" derived:"withdrawals.at" json:"at"`
}
