// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"database/sql"
)

type Document struct {
	ID          int64  `db:"id" derived:"documents.id" json:"id"`
	Path        string `db:"path" derived:"documents.path" json:"path"`
	Title       string `db:"title" derived:"documents.title" json:"title"`
	AddedAt     int64  `db:"added_at" derived:"documents.added_at" json:"added_at"`
	ContentHash string `db:"content_hash" derived:"documents.content_hash" json:"content_hash"`
	FragMode    string `db:"frag_mode" derived:"documents.frag_mode" json:"frag_mode"`
	FragRecipe  string `db:"frag_recipe" derived:"documents.frag_recipe" json:"frag_recipe"`
}

type Fragment struct {
	ID        int64  `db:"id" derived:"fragments.id" json:"id"`
	DocID     int64  `db:"doc_id" derived:"fragments.doc_id" json:"doc_id"`
	Page      int64  `db:"page" derived:"fragments.page" json:"page"`
	Ord       int64  `db:"ord" derived:"fragments.ord" json:"ord"`
	Text      string `db:"text" derived:"fragments.text" json:"text"`
	StartOff  int64  `db:"start_off" derived:"fragments.start_off" json:"start_off"`
	EndOff    int64  `db:"end_off" derived:"fragments.end_off" json:"end_off"`
	PageSpans string `db:"page_spans" derived:"fragments.page_spans" json:"page_spans"`
}

type FragmentVector struct {
	FragmentID int64  `db:"fragment_id" derived:"fragment_vectors.fragment_id" json:"fragment_id"`
	Dim        int64  `db:"dim" derived:"fragment_vectors.dim" json:"dim"`
	Vec        []byte `db:"vec" derived:"fragment_vectors.vec" json:"vec"`
}

type FragmentsFt struct {
	Text string `db:"text" derived:"fragments_fts.text" json:"text"`
}

type IndexMetum struct {
	Key       string `db:"key" derived:"index_meta.key" json:"key"`
	Value     string `db:"value" derived:"index_meta.value" json:"value"`
	UpdatedAt int64  `db:"updated_at" derived:"index_meta.updated_at" json:"updated_at"`
}

type IngestJob struct {
	ID         int64  `db:"id" derived:"ingest_jobs.id" json:"id"`
	Url        string `db:"url" derived:"ingest_jobs.url" json:"url"`
	Title      string `db:"title" derived:"ingest_jobs.title" json:"title"`
	State      string `db:"state" derived:"ingest_jobs.state" json:"state"`
	Error      string `db:"error" derived:"ingest_jobs.error" json:"error"`
	Fragments  int64  `db:"fragments" derived:"ingest_jobs.fragments" json:"fragments"`
	Mode       string `db:"mode" derived:"ingest_jobs.mode" json:"mode"`
	EnqueuedAt int64  `db:"enqueued_at" derived:"ingest_jobs.enqueued_at" json:"enqueued_at"`
	StartedAt  int64  `db:"started_at" derived:"ingest_jobs.started_at" json:"started_at"`
	FinishedAt int64  `db:"finished_at" derived:"ingest_jobs.finished_at" json:"finished_at"`
	OwnerPid   int64  `db:"owner_pid" derived:"ingest_jobs.owner_pid" json:"owner_pid"`
}

type JobStage struct {
	ID     int64  `db:"id" derived:"job_stages.id" json:"id"`
	JobID  int64  `db:"job_id" derived:"job_stages.job_id" json:"job_id"`
	Seq    int64  `db:"seq" derived:"job_stages.seq" json:"seq"`
	Name   string `db:"name" derived:"job_stages.name" json:"name"`
	Engine string `db:"engine" derived:"job_stages.engine" json:"engine"`
	State  string `db:"state" derived:"job_stages.state" json:"state"`
	Detail string `db:"detail" derived:"job_stages.detail" json:"detail"`
	At     int64  `db:"at" derived:"job_stages.at" json:"at"`
}

type MediaVector struct {
	MediaID int64  `db:"media_id" derived:"media_vectors.media_id" json:"media_id"`
	Dim     int64  `db:"dim" derived:"media_vectors.dim" json:"dim"`
	Vec     []byte `db:"vec" derived:"media_vectors.vec" json:"vec"`
	Space   string `db:"space" derived:"media_vectors.space" json:"space"`
}

type Medium struct {
	ID          int64         `db:"id" derived:"media.id" json:"id"`
	DocID       int64         `db:"doc_id" derived:"media.doc_id" json:"doc_id"`
	Page        int64         `db:"page" derived:"media.page" json:"page"`
	Ord         int64         `db:"ord" derived:"media.ord" json:"ord"`
	Kind        string        `db:"kind" derived:"media.kind" json:"kind"`
	ImagePath   string        `db:"image_path" derived:"media.image_path" json:"image_path"`
	Bbox        string        `db:"bbox" derived:"media.bbox" json:"bbox"`
	Description string        `db:"description" derived:"media.description" json:"description"`
	FragmentID  sql.NullInt64 `db:"fragment_id" derived:"media.fragment_id" json:"fragment_id"`
}

type OcrPage struct {
	DocID     int64  `db:"doc_id" derived:"ocr_pages.doc_id" json:"doc_id"`
	Page      int64  `db:"page" derived:"ocr_pages.page" json:"page"`
	Engine    string `db:"engine" derived:"ocr_pages.engine" json:"engine"`
	ImagePath string `db:"image_path" derived:"ocr_pages.image_path" json:"image_path"`
}

type OcrPageCache struct {
	ImgSha    string `db:"img_sha" derived:"ocr_page_cache.img_sha" json:"img_sha"`
	Engine    string `db:"engine" derived:"ocr_page_cache.engine" json:"engine"`
	Text      string `db:"text" derived:"ocr_page_cache.text" json:"text"`
	CreatedAt int64  `db:"created_at" derived:"ocr_page_cache.created_at" json:"created_at"`
}

type ShingleIndex struct {
	Hash  int64 `db:"hash" derived:"shingle_index.hash" json:"hash"`
	DocID int64 `db:"doc_id" derived:"shingle_index.doc_id" json:"doc_id"`
	Page  int64 `db:"page" derived:"shingle_index.page" json:"page"`
}

type ShinglePage struct {
	DocID   int64  `db:"doc_id" derived:"shingle_pages.doc_id" json:"doc_id"`
	Page    int64  `db:"page" derived:"shingle_pages.page" json:"page"`
	Chars   int64  `db:"chars" derived:"shingle_pages.chars" json:"chars"`
	Total   int64  `db:"total" derived:"shingle_pages.total" json:"total"`
	Sampled int64  `db:"sampled" derived:"shingle_pages.sampled" json:"sampled"`
	Recipe  string `db:"recipe" derived:"shingle_pages.recipe" json:"recipe"`
}

type Tombstone struct {
	Path string `db:"path" derived:"tombstones.path" json:"path"`
}
