// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: query.sql

package db

import (
	"context"
	"database/sql"
)

const abortJob = `-- name: AbortJob :execrows
UPDATE ingest_jobs SET state='error', error=?, finished_at=?
WHERE id=? AND state='running'
`

type AbortJobParams struct {
	Error      string `db:"error" derived:"ingest_jobs.error" json:"error"`
	FinishedAt int64  `db:"finished_at" derived:"ingest_jobs.finished_at" json:"finished_at"`
	ID         int64  `db:"id" derived:"ingest_jobs.id" json:"id"`
}

func (q *Queries) AbortJob(ctx context.Context, arg AbortJobParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, abortJob, arg.Error, arg.FinishedAt, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const cancelJob = `-- name: CancelJob :execrows
DELETE FROM ingest_jobs WHERE id=? AND state='pending'
`

func (q *Queries) CancelJob(ctx context.Context, id int64) (int64, error) {
	result, err := q.db.ExecContext(ctx, cancelJob, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const completeJob = `-- name: CompleteJob :exec
UPDATE ingest_jobs SET state='done', fragments=?, mode=?, error='', finished_at=? WHERE id=?
`

type CompleteJobParams struct {
	Fragments  int64  `db:"fragments" derived:"ingest_jobs.fragments" json:"fragments"`
	Mode       string `db:"mode" derived:"ingest_jobs.mode" json:"mode"`
	FinishedAt int64  `db:"finished_at" derived:"ingest_jobs.finished_at" json:"finished_at"`
	ID         int64  `db:"id" derived:"ingest_jobs.id" json:"id"`
}

func (q *Queries) CompleteJob(ctx context.Context, arg CompleteJobParams) error {
	_, err := q.db.ExecContext(ctx, completeJob,
		arg.Fragments,
		arg.Mode,
		arg.FinishedAt,
		arg.ID,
	)
	return err
}

const countDocuments = `-- name: CountDocuments :one
SELECT COUNT(*) AS n FROM documents
`

func (q *Queries) CountDocuments(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, countDocuments)
	var n int64
	err := row.Scan(&n)
	return n, err
}

const countFragments = `-- name: CountFragments :one
SELECT COUNT(*) AS n FROM fragments
`

// ===== fragments =====
func (q *Queries) CountFragments(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, countFragments)
	var n int64
	err := row.Scan(&n)
	return n, err
}

const deleteDocumentByPath = `-- name: DeleteDocumentByPath :exec
DELETE FROM documents WHERE path = ?
`

func (q *Queries) DeleteDocumentByPath(ctx context.Context, path string) error {
	_, err := q.db.ExecContext(ctx, deleteDocumentByPath, path)
	return err
}

const deleteFragmentsByDoc = `-- name: DeleteFragmentsByDoc :exec
DELETE FROM fragments WHERE doc_id = ?
`

func (q *Queries) DeleteFragmentsByDoc(ctx context.Context, docID int64) error {
	_, err := q.db.ExecContext(ctx, deleteFragmentsByDoc, docID)
	return err
}

const deleteMediaByDoc = `-- name: DeleteMediaByDoc :exec
DELETE FROM media WHERE doc_id = ?
`

func (q *Queries) DeleteMediaByDoc(ctx context.Context, docID int64) error {
	_, err := q.db.ExecContext(ctx, deleteMediaByDoc, docID)
	return err
}

const deleteOcrPagesByDoc = `-- name: DeleteOcrPagesByDoc :exec
DELETE FROM ocr_pages WHERE doc_id = ?
`

func (q *Queries) DeleteOcrPagesByDoc(ctx context.Context, docID int64) error {
	_, err := q.db.ExecContext(ctx, deleteOcrPagesByDoc, docID)
	return err
}

const deleteTombstone = `-- name: DeleteTombstone :exec
DELETE FROM tombstones WHERE path = ?
`

func (q *Queries) DeleteTombstone(ctx context.Context, path string) error {
	_, err := q.db.ExecContext(ctx, deleteTombstone, path)
	return err
}

const enqueueJob = `-- name: EnqueueJob :one
INSERT INTO ingest_jobs(url, title, state, enqueued_at) VALUES(?, ?, 'pending', ?) RETURNING id
`

type EnqueueJobParams struct {
	Url        string `db:"url" derived:"ingest_jobs.url" json:"url"`
	Title      string `db:"title" derived:"ingest_jobs.title" json:"title"`
	EnqueuedAt int64  `db:"enqueued_at" derived:"ingest_jobs.enqueued_at" json:"enqueued_at"`
}

// ===== ingest_jobs =====
func (q *Queries) EnqueueJob(ctx context.Context, arg EnqueueJobParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, enqueueJob, arg.Url, arg.Title, arg.EnqueuedAt)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const exportFragments = `-- name: ExportFragments :many
SELECT f.page, f.ord, f.text, f.start_off, f.end_off, f.page_spans, fv.vec
FROM fragments f LEFT JOIN fragment_vectors fv ON fv.fragment_id = f.id
WHERE f.doc_id = ? ORDER BY f.page, f.ord
`

type ExportFragmentsRow struct {
	Page      int64  `db:"page" derived:"fragments.page" json:"page"`
	Ord       int64  `db:"ord" derived:"fragments.ord" json:"ord"`
	Text      string `db:"text" derived:"fragments.text" json:"text"`
	StartOff  int64  `db:"start_off" derived:"fragments.start_off" json:"start_off"`
	EndOff    int64  `db:"end_off" derived:"fragments.end_off" json:"end_off"`
	PageSpans string `db:"page_spans" derived:"fragments.page_spans" json:"page_spans"`
	Vec       []byte `db:"vec" derived:"fragment_vectors.vec" json:"vec"`
}

func (q *Queries) ExportFragments(ctx context.Context, docID int64) ([]ExportFragmentsRow, error) {
	rows, err := q.db.QueryContext(ctx, exportFragments, docID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ExportFragmentsRow
	for rows.Next() {
		var i ExportFragmentsRow
		if err := rows.Scan(
			&i.Page,
			&i.Ord,
			&i.Text,
			&i.StartOff,
			&i.EndOff,
			&i.PageSpans,
			&i.Vec,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const failJob = `-- name: FailJob :exec
UPDATE ingest_jobs SET state='error', error=?, finished_at=? WHERE id=?
`

type FailJobParams struct {
	Error      string `db:"error" derived:"ingest_jobs.error" json:"error"`
	FinishedAt int64  `db:"finished_at" derived:"ingest_jobs.finished_at" json:"finished_at"`
	ID         int64  `db:"id" derived:"ingest_jobs.id" json:"id"`
}

func (q *Queries) FailJob(ctx context.Context, arg FailJobParams) error {
	_, err := q.db.ExecContext(ctx, failJob, arg.Error, arg.FinishedAt, arg.ID)
	return err
}

const getDocumentByPath = `-- name: GetDocumentByPath :one

SELECT id, path, title, added_at FROM documents WHERE path = ?
`

type GetDocumentByPathRow struct {
	ID      int64  `db:"id" derived:"documents.id" json:"id"`
	Path    string `db:"path" derived:"documents.path" json:"path"`
	Title   string `db:"title" derived:"documents.title" json:"title"`
	AddedAt int64  `db:"added_at" derived:"documents.added_at" json:"added_at"`
}

// Relational CRUD for the raglit Store. FTS5 search + vector cosine are NOT here
// (sqlc can't parse fts5); they stay as raw SQL in store.go.
// ===== documents =====
func (q *Queries) GetDocumentByPath(ctx context.Context, path string) (GetDocumentByPathRow, error) {
	row := q.db.QueryRowContext(ctx, getDocumentByPath, path)
	var i GetDocumentByPathRow
	err := row.Scan(
		&i.ID,
		&i.Path,
		&i.Title,
		&i.AddedAt,
	)
	return i, err
}

const getDocumentFrag = `-- name: GetDocumentFrag :one
SELECT frag_mode, frag_recipe FROM documents WHERE id = ?
`

type GetDocumentFragRow struct {
	FragMode   string `db:"frag_mode" derived:"documents.frag_mode" json:"frag_mode"`
	FragRecipe string `db:"frag_recipe" derived:"documents.frag_recipe" json:"frag_recipe"`
}

func (q *Queries) GetDocumentFrag(ctx context.Context, id int64) (GetDocumentFragRow, error) {
	row := q.db.QueryRowContext(ctx, getDocumentFrag, id)
	var i GetDocumentFragRow
	err := row.Scan(&i.FragMode, &i.FragRecipe)
	return i, err
}

const getDocumentHash = `-- name: GetDocumentHash :one
SELECT content_hash FROM documents WHERE path = ?
`

// ===== content-hash dedup =====
func (q *Queries) GetDocumentHash(ctx context.Context, path string) (string, error) {
	row := q.db.QueryRowContext(ctx, getDocumentHash, path)
	var content_hash string
	err := row.Scan(&content_hash)
	return content_hash, err
}

const getJob = `-- name: GetJob :one
SELECT id, url, title, state, error, fragments, mode, enqueued_at, started_at, finished_at, owner_pid, lane
FROM ingest_jobs WHERE id = ?
`

func (q *Queries) GetJob(ctx context.Context, id int64) (IngestJob, error) {
	row := q.db.QueryRowContext(ctx, getJob, id)
	var i IngestJob
	err := row.Scan(
		&i.ID,
		&i.Url,
		&i.Title,
		&i.State,
		&i.Error,
		&i.Fragments,
		&i.Mode,
		&i.EnqueuedAt,
		&i.StartedAt,
		&i.FinishedAt,
		&i.OwnerPid,
		&i.Lane,
	)
	return i, err
}

const getOldestPendingJob = `-- name: GetOldestPendingJob :one
SELECT id, url, title, enqueued_at FROM ingest_jobs WHERE state='pending' ORDER BY id LIMIT 1
`

type GetOldestPendingJobRow struct {
	ID         int64  `db:"id" derived:"ingest_jobs.id" json:"id"`
	Url        string `db:"url" derived:"ingest_jobs.url" json:"url"`
	Title      string `db:"title" derived:"ingest_jobs.title" json:"title"`
	EnqueuedAt int64  `db:"enqueued_at" derived:"ingest_jobs.enqueued_at" json:"enqueued_at"`
}

func (q *Queries) GetOldestPendingJob(ctx context.Context) (GetOldestPendingJobRow, error) {
	row := q.db.QueryRowContext(ctx, getOldestPendingJob)
	var i GetOldestPendingJobRow
	err := row.Scan(
		&i.ID,
		&i.Url,
		&i.Title,
		&i.EnqueuedAt,
	)
	return i, err
}

const getOldestPendingJobInLane = `-- name: GetOldestPendingJobInLane :one
SELECT id, url, title, enqueued_at FROM ingest_jobs
WHERE state='pending' AND lane = ? ORDER BY id LIMIT 1
`

type GetOldestPendingJobInLaneRow struct {
	ID         int64  `db:"id" derived:"ingest_jobs.id" json:"id"`
	Url        string `db:"url" derived:"ingest_jobs.url" json:"url"`
	Title      string `db:"title" derived:"ingest_jobs.title" json:"title"`
	EnqueuedAt int64  `db:"enqueued_at" derived:"ingest_jobs.enqueued_at" json:"enqueued_at"`
}

func (q *Queries) GetOldestPendingJobInLane(ctx context.Context, lane string) (GetOldestPendingJobInLaneRow, error) {
	row := q.db.QueryRowContext(ctx, getOldestPendingJobInLane, lane)
	var i GetOldestPendingJobInLaneRow
	err := row.Scan(
		&i.ID,
		&i.Url,
		&i.Title,
		&i.EnqueuedAt,
	)
	return i, err
}

const getPageImagePath = `-- name: GetPageImagePath :one
SELECT p.image_path FROM ocr_pages p JOIN documents d ON d.id = p.doc_id
WHERE d.path = ? AND p.page = ?
`

type GetPageImagePathParams struct {
	Path string `db:"path" derived:"documents.path" json:"path"`
	Page int64  `db:"page" derived:"ocr_pages.page" json:"page"`
}

func (q *Queries) GetPageImagePath(ctx context.Context, arg GetPageImagePathParams) (string, error) {
	row := q.db.QueryRowContext(ctx, getPageImagePath, arg.Path, arg.Page)
	var image_path string
	err := row.Scan(&image_path)
	return image_path, err
}

const getReadingForDoc = `-- name: GetReadingForDoc :one
SELECT id, source_sha256, source_path, doc_path, method, level, produced_by, ruled_by, at
FROM readings WHERE doc_path = ?
`

func (q *Queries) GetReadingForDoc(ctx context.Context, docPath string) (Reading, error) {
	row := q.db.QueryRowContext(ctx, getReadingForDoc, docPath)
	var i Reading
	err := row.Scan(
		&i.ID,
		&i.SourceSha256,
		&i.SourcePath,
		&i.DocPath,
		&i.Method,
		&i.Level,
		&i.ProducedBy,
		&i.RuledBy,
		&i.At,
	)
	return i, err
}

const insertFragment = `-- name: InsertFragment :one
INSERT INTO fragments(doc_id, page, ord, text, start_off, end_off, page_spans, origin)
VALUES(?, ?, ?, ?, ?, ?, ?, ?) RETURNING id
`

type InsertFragmentParams struct {
	DocID     int64  `db:"doc_id" derived:"fragments.doc_id" json:"doc_id"`
	Page      int64  `db:"page" derived:"fragments.page" json:"page"`
	Ord       int64  `db:"ord" derived:"fragments.ord" json:"ord"`
	Text      string `db:"text" derived:"fragments.text" json:"text"`
	StartOff  int64  `db:"start_off" derived:"fragments.start_off" json:"start_off"`
	EndOff    int64  `db:"end_off" derived:"fragments.end_off" json:"end_off"`
	PageSpans string `db:"page_spans" derived:"fragments.page_spans" json:"page_spans"`
	Origin    string `db:"origin" derived:"fragments.origin" json:"origin"`
}

// origin marks text nobody wrote: 'described' for a model's account of an image
// (indextext.go), 'identity' for a generated caption (identity.go). Empty is
// transcription, and the only kind that may be quoted as the record.
func (q *Queries) InsertFragment(ctx context.Context, arg InsertFragmentParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, insertFragment,
		arg.DocID,
		arg.Page,
		arg.Ord,
		arg.Text,
		arg.StartOff,
		arg.EndOff,
		arg.PageSpans,
		arg.Origin,
	)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const insertMedia = `-- name: InsertMedia :one
INSERT INTO media(doc_id, page, ord, kind, image_path, bbox, description, fragment_id)
VALUES(?,?,?,?,?,?,?,?) RETURNING id
`

type InsertMediaParams struct {
	DocID       int64         `db:"doc_id" derived:"media.doc_id" json:"doc_id"`
	Page        int64         `db:"page" derived:"media.page" json:"page"`
	Ord         int64         `db:"ord" derived:"media.ord" json:"ord"`
	Kind        string        `db:"kind" derived:"media.kind" json:"kind"`
	ImagePath   string        `db:"image_path" derived:"media.image_path" json:"image_path"`
	Bbox        string        `db:"bbox" derived:"media.bbox" json:"bbox"`
	Description string        `db:"description" derived:"media.description" json:"description"`
	FragmentID  sql.NullInt64 `db:"fragment_id" derived:"media.fragment_id" json:"fragment_id"`
}

// ===== media (figures explained into fragments) =====
func (q *Queries) InsertMedia(ctx context.Context, arg InsertMediaParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, insertMedia,
		arg.DocID,
		arg.Page,
		arg.Ord,
		arg.Kind,
		arg.ImagePath,
		arg.Bbox,
		arg.Description,
		arg.FragmentID,
	)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const insertMediaVector = `-- name: InsertMediaVector :exec
INSERT INTO media_vectors(media_id, dim, vec, space) VALUES(?,?,?,?)
`

type InsertMediaVectorParams struct {
	MediaID int64  `db:"media_id" derived:"media_vectors.media_id" json:"media_id"`
	Dim     int64  `db:"dim" derived:"media_vectors.dim" json:"dim"`
	Vec     []byte `db:"vec" derived:"media_vectors.vec" json:"vec"`
	Space   string `db:"space" derived:"media_vectors.space" json:"space"`
}

func (q *Queries) InsertMediaVector(ctx context.Context, arg InsertMediaVectorParams) error {
	_, err := q.db.ExecContext(ctx, insertMediaVector,
		arg.MediaID,
		arg.Dim,
		arg.Vec,
		arg.Space,
	)
	return err
}

const insertStage = `-- name: InsertStage :exec
INSERT INTO job_stages(job_id, seq, name, engine, state, detail, at) VALUES(?,?,?,?,?,?,?)
`

type InsertStageParams struct {
	JobID  int64  `db:"job_id" derived:"job_stages.job_id" json:"job_id"`
	Seq    int64  `db:"seq" derived:"job_stages.seq" json:"seq"`
	Name   string `db:"name" derived:"job_stages.name" json:"name"`
	Engine string `db:"engine" derived:"job_stages.engine" json:"engine"`
	State  string `db:"state" derived:"job_stages.state" json:"state"`
	Detail string `db:"detail" derived:"job_stages.detail" json:"detail"`
	At     int64  `db:"at" derived:"job_stages.at" json:"at"`
}

// ===== job_stages =====
func (q *Queries) InsertStage(ctx context.Context, arg InsertStageParams) error {
	_, err := q.db.ExecContext(ctx, insertStage,
		arg.JobID,
		arg.Seq,
		arg.Name,
		arg.Engine,
		arg.State,
		arg.Detail,
		arg.At,
	)
	return err
}

const insertTombstone = `-- name: InsertTombstone :exec
INSERT OR IGNORE INTO tombstones(path) VALUES(?)
`

// ===== tombstones (branch storage) =====
func (q *Queries) InsertTombstone(ctx context.Context, path string) error {
	_, err := q.db.ExecContext(ctx, insertTombstone, path)
	return err
}

const insertVector = `-- name: InsertVector :exec
INSERT INTO fragment_vectors(fragment_id, dim, vec) VALUES(?, ?, ?)
`

type InsertVectorParams struct {
	FragmentID int64  `db:"fragment_id" derived:"fragment_vectors.fragment_id" json:"fragment_id"`
	Dim        int64  `db:"dim" derived:"fragment_vectors.dim" json:"dim"`
	Vec        []byte `db:"vec" derived:"fragment_vectors.vec" json:"vec"`
}

// ===== fragment_vectors =====
func (q *Queries) InsertVector(ctx context.Context, arg InsertVectorParams) error {
	_, err := q.db.ExecContext(ctx, insertVector, arg.FragmentID, arg.Dim, arg.Vec)
	return err
}

const jobStateCounts = `-- name: JobStateCounts :many
SELECT state, COUNT(*) AS n FROM ingest_jobs GROUP BY state
`

type JobStateCountsRow struct {
	State string `db:"state" derived:"ingest_jobs.state" json:"state"`
	N     int64  `db:"n" json:"n"`
}

func (q *Queries) JobStateCounts(ctx context.Context) ([]JobStateCountsRow, error) {
	rows, err := q.db.QueryContext(ctx, jobStateCounts)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []JobStateCountsRow
	for rows.Next() {
		var i JobStateCountsRow
		if err := rows.Scan(&i.State, &i.N); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const laneQueueCounts = `-- name: LaneQueueCounts :many
SELECT lane, state, COUNT(*) AS n FROM ingest_jobs
WHERE state IN ('pending','running') GROUP BY lane, state
`

type LaneQueueCountsRow struct {
	Lane  string `db:"lane" derived:"ingest_jobs.lane" json:"lane"`
	State string `db:"state" derived:"ingest_jobs.state" json:"state"`
	N     int64  `db:"n" json:"n"`
}

func (q *Queries) LaneQueueCounts(ctx context.Context) ([]LaneQueueCountsRow, error) {
	rows, err := q.db.QueryContext(ctx, laneQueueCounts)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []LaneQueueCountsRow
	for rows.Next() {
		var i LaneQueueCountsRow
		if err := rows.Scan(&i.Lane, &i.State, &i.N); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listActiveJobs = `-- name: ListActiveJobs :many
SELECT id, url, state FROM ingest_jobs
WHERE state IN ('running','pending')
ORDER BY CASE state WHEN 'running' THEN 0 ELSE 1 END, id
`

type ListActiveJobsRow struct {
	ID    int64  `db:"id" derived:"ingest_jobs.id" json:"id"`
	Url   string `db:"url" derived:"ingest_jobs.url" json:"url"`
	State string `db:"state" derived:"ingest_jobs.state" json:"state"`
}

func (q *Queries) ListActiveJobs(ctx context.Context) ([]ListActiveJobsRow, error) {
	rows, err := q.db.QueryContext(ctx, listActiveJobs)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListActiveJobsRow
	for rows.Next() {
		var i ListActiveJobsRow
		if err := rows.Scan(&i.ID, &i.Url, &i.State); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAllReadings = `-- name: ListAllReadings :many
SELECT id, source_sha256, source_path, doc_path, method, level, produced_by, ruled_by, at
FROM readings ORDER BY source_sha256, at, id
`

func (q *Queries) ListAllReadings(ctx context.Context) ([]Reading, error) {
	rows, err := q.db.QueryContext(ctx, listAllReadings)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Reading
	for rows.Next() {
		var i Reading
		if err := rows.Scan(
			&i.ID,
			&i.SourceSha256,
			&i.SourcePath,
			&i.DocPath,
			&i.Method,
			&i.Level,
			&i.ProducedBy,
			&i.RuledBy,
			&i.At,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDocumentPaths = `-- name: ListDocumentPaths :many
SELECT path FROM documents
`

func (q *Queries) ListDocumentPaths(ctx context.Context) ([]string, error) {
	rows, err := q.db.QueryContext(ctx, listDocumentPaths)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var path string
		if err := rows.Scan(&path); err != nil {
			return nil, err
		}
		items = append(items, path)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDocumentSummaries = `-- name: ListDocumentSummaries :many
SELECT d.id, d.path, d.title, d.added_at, d.frag_mode,
       (SELECT COUNT(*) FROM fragments f WHERE f.doc_id = d.id) AS fragments
FROM documents d ORDER BY d.added_at DESC
`

type ListDocumentSummariesRow struct {
	ID        int64  `db:"id" derived:"documents.id" json:"id"`
	Path      string `db:"path" derived:"documents.path" json:"path"`
	Title     string `db:"title" derived:"documents.title" json:"title"`
	AddedAt   int64  `db:"added_at" derived:"documents.added_at" json:"added_at"`
	FragMode  string `db:"frag_mode" derived:"documents.frag_mode" json:"frag_mode"`
	Fragments int64  `db:"fragments" json:"fragments"`
}

func (q *Queries) ListDocumentSummaries(ctx context.Context) ([]ListDocumentSummariesRow, error) {
	rows, err := q.db.QueryContext(ctx, listDocumentSummaries)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListDocumentSummariesRow
	for rows.Next() {
		var i ListDocumentSummariesRow
		if err := rows.Scan(
			&i.ID,
			&i.Path,
			&i.Title,
			&i.AddedAt,
			&i.FragMode,
			&i.Fragments,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listFragmentTextByPage = `-- name: ListFragmentTextByPage :many
SELECT text FROM fragments WHERE doc_id = ? AND page = ? ORDER BY ord
`

type ListFragmentTextByPageParams struct {
	DocID int64 `db:"doc_id" derived:"fragments.doc_id" json:"doc_id"`
	Page  int64 `db:"page" derived:"fragments.page" json:"page"`
}

func (q *Queries) ListFragmentTextByPage(ctx context.Context, arg ListFragmentTextByPageParams) ([]string, error) {
	rows, err := q.db.QueryContext(ctx, listFragmentTextByPage, arg.DocID, arg.Page)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var text string
		if err := rows.Scan(&text); err != nil {
			return nil, err
		}
		items = append(items, text)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listFragmentsForDoc = `-- name: ListFragmentsForDoc :many
SELECT page, ord, text, start_off, end_off FROM fragments WHERE doc_id = ? ORDER BY page, ord
`

type ListFragmentsForDocRow struct {
	Page     int64  `db:"page" derived:"fragments.page" json:"page"`
	Ord      int64  `db:"ord" derived:"fragments.ord" json:"ord"`
	Text     string `db:"text" derived:"fragments.text" json:"text"`
	StartOff int64  `db:"start_off" derived:"fragments.start_off" json:"start_off"`
	EndOff   int64  `db:"end_off" derived:"fragments.end_off" json:"end_off"`
}

func (q *Queries) ListFragmentsForDoc(ctx context.Context, docID int64) ([]ListFragmentsForDocRow, error) {
	rows, err := q.db.QueryContext(ctx, listFragmentsForDoc, docID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListFragmentsForDocRow
	for rows.Next() {
		var i ListFragmentsForDocRow
		if err := rows.Scan(
			&i.Page,
			&i.Ord,
			&i.Text,
			&i.StartOff,
			&i.EndOff,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listJobStages = `-- name: ListJobStages :many
SELECT id, seq, name, engine, state, detail, at FROM job_stages WHERE job_id = ? ORDER BY id
`

type ListJobStagesRow struct {
	ID     int64  `db:"id" derived:"job_stages.id" json:"id"`
	Seq    int64  `db:"seq" derived:"job_stages.seq" json:"seq"`
	Name   string `db:"name" derived:"job_stages.name" json:"name"`
	Engine string `db:"engine" derived:"job_stages.engine" json:"engine"`
	State  string `db:"state" derived:"job_stages.state" json:"state"`
	Detail string `db:"detail" derived:"job_stages.detail" json:"detail"`
	At     int64  `db:"at" derived:"job_stages.at" json:"at"`
}

// ORDER BY id, not seq. A retried job appends a WHOLE SECOND RUN of stages under
// the same job_id, and seq restarts at 1 each time — so ordering by seq
// interleaves the runs and the account becomes unreadable. Job 927 on the delano
// index is four runs, and read as "fetch, fetch, fetch, fetch, extract, extract,
// …" with no way to tell which failure belonged to which attempt. id is
// insertion order, which is chronological, which keeps a run together — and it
// is the only stable key a stage has, since (job_id, seq) names up to four rows.
func (q *Queries) ListJobStages(ctx context.Context, jobID int64) ([]ListJobStagesRow, error) {
	rows, err := q.db.QueryContext(ctx, listJobStages, jobID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListJobStagesRow
	for rows.Next() {
		var i ListJobStagesRow
		if err := rows.Scan(
			&i.ID,
			&i.Seq,
			&i.Name,
			&i.Engine,
			&i.State,
			&i.Detail,
			&i.At,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listJobs = `-- name: ListJobs :many
SELECT id, url, title, state, error, fragments, mode, enqueued_at, started_at, finished_at, owner_pid, lane
FROM ingest_jobs
`

// The projection must carry EVERY column of ingest_jobs. This is scanned into
// the full-table IngestJob struct through metaquery, which validates the two
// against each other and refuses a mismatch -- so adding a column to the table
// and not to this list does not silently drop a field, it breaks the jobs list
// outright with "shape mismatch: field IngestJob.Lane not in projection".
func (q *Queries) ListJobs(ctx context.Context) ([]IngestJob, error) {
	rows, err := q.db.QueryContext(ctx, listJobs)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []IngestJob
	for rows.Next() {
		var i IngestJob
		if err := rows.Scan(
			&i.ID,
			&i.Url,
			&i.Title,
			&i.State,
			&i.Error,
			&i.Fragments,
			&i.Mode,
			&i.EnqueuedAt,
			&i.StartedAt,
			&i.FinishedAt,
			&i.OwnerPid,
			&i.Lane,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMediaByDoc = `-- name: ListMediaByDoc :many
SELECT page, ord, kind, image_path, bbox, description, fragment_id
FROM media WHERE doc_id = ? ORDER BY page, ord
`

type ListMediaByDocRow struct {
	Page        int64         `db:"page" derived:"media.page" json:"page"`
	Ord         int64         `db:"ord" derived:"media.ord" json:"ord"`
	Kind        string        `db:"kind" derived:"media.kind" json:"kind"`
	ImagePath   string        `db:"image_path" derived:"media.image_path" json:"image_path"`
	Bbox        string        `db:"bbox" derived:"media.bbox" json:"bbox"`
	Description string        `db:"description" derived:"media.description" json:"description"`
	FragmentID  sql.NullInt64 `db:"fragment_id" derived:"media.fragment_id" json:"fragment_id"`
}

func (q *Queries) ListMediaByDoc(ctx context.Context, docID int64) ([]ListMediaByDocRow, error) {
	rows, err := q.db.QueryContext(ctx, listMediaByDoc, docID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListMediaByDocRow
	for rows.Next() {
		var i ListMediaByDocRow
		if err := rows.Scan(
			&i.Page,
			&i.Ord,
			&i.Kind,
			&i.ImagePath,
			&i.Bbox,
			&i.Description,
			&i.FragmentID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMediaByFragment = `-- name: ListMediaByFragment :many
SELECT page, ord, kind, image_path, bbox, description
FROM media WHERE fragment_id = ? ORDER BY ord
`

type ListMediaByFragmentRow struct {
	Page        int64  `db:"page" derived:"media.page" json:"page"`
	Ord         int64  `db:"ord" derived:"media.ord" json:"ord"`
	Kind        string `db:"kind" derived:"media.kind" json:"kind"`
	ImagePath   string `db:"image_path" derived:"media.image_path" json:"image_path"`
	Bbox        string `db:"bbox" derived:"media.bbox" json:"bbox"`
	Description string `db:"description" derived:"media.description" json:"description"`
}

func (q *Queries) ListMediaByFragment(ctx context.Context, fragmentID sql.NullInt64) ([]ListMediaByFragmentRow, error) {
	rows, err := q.db.QueryContext(ctx, listMediaByFragment, fragmentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListMediaByFragmentRow
	for rows.Next() {
		var i ListMediaByFragmentRow
		if err := rows.Scan(
			&i.Page,
			&i.Ord,
			&i.Kind,
			&i.ImagePath,
			&i.Bbox,
			&i.Description,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listOcrPagesByDoc = `-- name: ListOcrPagesByDoc :many
SELECT page, engine, image_path FROM ocr_pages WHERE doc_id = ? ORDER BY page
`

type ListOcrPagesByDocRow struct {
	Page      int64  `db:"page" derived:"ocr_pages.page" json:"page"`
	Engine    string `db:"engine" derived:"ocr_pages.engine" json:"engine"`
	ImagePath string `db:"image_path" derived:"ocr_pages.image_path" json:"image_path"`
}

func (q *Queries) ListOcrPagesByDoc(ctx context.Context, docID int64) ([]ListOcrPagesByDocRow, error) {
	rows, err := q.db.QueryContext(ctx, listOcrPagesByDoc, docID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListOcrPagesByDocRow
	for rows.Next() {
		var i ListOcrPagesByDocRow
		if err := rows.Scan(&i.Page, &i.Engine, &i.ImagePath); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listReadingsOfSource = `-- name: ListReadingsOfSource :many
SELECT id, source_sha256, source_path, doc_path, method, level, produced_by, ruled_by, at
FROM readings WHERE source_sha256 = ? AND source_sha256 <> '' ORDER BY at, id
`

func (q *Queries) ListReadingsOfSource(ctx context.Context, sourceSha256 string) ([]Reading, error) {
	rows, err := q.db.QueryContext(ctx, listReadingsOfSource, sourceSha256)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Reading
	for rows.Next() {
		var i Reading
		if err := rows.Scan(
			&i.ID,
			&i.SourceSha256,
			&i.SourcePath,
			&i.DocPath,
			&i.Method,
			&i.Level,
			&i.ProducedBy,
			&i.RuledBy,
			&i.At,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRunningJobOwners = `-- name: ListRunningJobOwners :many
SELECT id, url, owner_pid, started_at FROM ingest_jobs WHERE state='running'
`

type ListRunningJobOwnersRow struct {
	ID        int64  `db:"id" derived:"ingest_jobs.id" json:"id"`
	Url       string `db:"url" derived:"ingest_jobs.url" json:"url"`
	OwnerPid  int64  `db:"owner_pid" derived:"ingest_jobs.owner_pid" json:"owner_pid"`
	StartedAt int64  `db:"started_at" derived:"ingest_jobs.started_at" json:"started_at"`
}

func (q *Queries) ListRunningJobOwners(ctx context.Context) ([]ListRunningJobOwnersRow, error) {
	rows, err := q.db.QueryContext(ctx, listRunningJobOwners)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListRunningJobOwnersRow
	for rows.Next() {
		var i ListRunningJobOwnersRow
		if err := rows.Scan(
			&i.ID,
			&i.Url,
			&i.OwnerPid,
			&i.StartedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTombstones = `-- name: ListTombstones :many
SELECT path FROM tombstones
`

func (q *Queries) ListTombstones(ctx context.Context) ([]string, error) {
	rows, err := q.db.QueryContext(ctx, listTombstones)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var path string
		if err := rows.Scan(&path); err != nil {
			return nil, err
		}
		items = append(items, path)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUnlanedPendingJobs = `-- name: ListUnlanedPendingJobs :many
SELECT id, url FROM ingest_jobs WHERE state='pending' AND lane = ''
`

type ListUnlanedPendingJobsRow struct {
	ID  int64  `db:"id" derived:"ingest_jobs.id" json:"id"`
	Url string `db:"url" derived:"ingest_jobs.url" json:"url"`
}

func (q *Queries) ListUnlanedPendingJobs(ctx context.Context) ([]ListUnlanedPendingJobsRow, error) {
	rows, err := q.db.QueryContext(ctx, listUnlanedPendingJobs)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListUnlanedPendingJobsRow
	for rows.Next() {
		var i ListUnlanedPendingJobsRow
		if err := rows.Scan(&i.ID, &i.Url); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const matchDocumentsLike = `-- name: MatchDocumentsLike :many
SELECT path, title FROM documents
WHERE lower(path) LIKE ? OR lower(title) LIKE ?
ORDER BY added_at DESC
`

type MatchDocumentsLikeParams struct {
	Path  string `db:"path" derived:"documents.path" json:"path"`
	Title string `db:"title" derived:"documents.title" json:"title"`
}

type MatchDocumentsLikeRow struct {
	Path  string `db:"path" derived:"documents.path" json:"path"`
	Title string `db:"title" derived:"documents.title" json:"title"`
}

func (q *Queries) MatchDocumentsLike(ctx context.Context, arg MatchDocumentsLikeParams) ([]MatchDocumentsLikeRow, error) {
	rows, err := q.db.QueryContext(ctx, matchDocumentsLike, arg.Path, arg.Title)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []MatchDocumentsLikeRow
	for rows.Next() {
		var i MatchDocumentsLikeRow
		if err := rows.Scan(&i.Path, &i.Title); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const ocrEngineCountsByDoc = `-- name: OcrEngineCountsByDoc :many
SELECT engine, COUNT(*) AS n FROM ocr_pages WHERE doc_id = ? GROUP BY engine
`

type OcrEngineCountsByDocRow struct {
	Engine string `db:"engine" derived:"ocr_pages.engine" json:"engine"`
	N      int64  `db:"n" json:"n"`
}

func (q *Queries) OcrEngineCountsByDoc(ctx context.Context, docID int64) ([]OcrEngineCountsByDocRow, error) {
	rows, err := q.db.QueryContext(ctx, ocrEngineCountsByDoc, docID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []OcrEngineCountsByDocRow
	for rows.Next() {
		var i OcrEngineCountsByDocRow
		if err := rows.Scan(&i.Engine, &i.N); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const recentDoneDurations = `-- name: RecentDoneDurations :many
SELECT started_at, finished_at FROM ingest_jobs
WHERE state='done' AND started_at>0 AND finished_at>=started_at
ORDER BY finished_at DESC LIMIT 10
`

type RecentDoneDurationsRow struct {
	StartedAt  int64 `db:"started_at" derived:"ingest_jobs.started_at" json:"started_at"`
	FinishedAt int64 `db:"finished_at" derived:"ingest_jobs.finished_at" json:"finished_at"`
}

func (q *Queries) RecentDoneDurations(ctx context.Context) ([]RecentDoneDurationsRow, error) {
	rows, err := q.db.QueryContext(ctx, recentDoneDurations)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []RecentDoneDurationsRow
	for rows.Next() {
		var i RecentDoneDurationsRow
		if err := rows.Scan(&i.StartedAt, &i.FinishedAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const retryJob = `-- name: RetryJob :execrows
UPDATE ingest_jobs SET state='pending', error='', started_at=0, finished_at=0, fragments=0
WHERE id=? AND state IN ('error','done')
`

func (q *Queries) RetryJob(ctx context.Context, id int64) (int64, error) {
	result, err := q.db.ExecContext(ctx, retryJob, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const setDocumentFrag = `-- name: SetDocumentFrag :exec
UPDATE documents SET frag_mode = ?, frag_recipe = ? WHERE id = ?
`

type SetDocumentFragParams struct {
	FragMode   string `db:"frag_mode" derived:"documents.frag_mode" json:"frag_mode"`
	FragRecipe string `db:"frag_recipe" derived:"documents.frag_recipe" json:"frag_recipe"`
	ID         int64  `db:"id" derived:"documents.id" json:"id"`
}

func (q *Queries) SetDocumentFrag(ctx context.Context, arg SetDocumentFragParams) error {
	_, err := q.db.ExecContext(ctx, setDocumentFrag, arg.FragMode, arg.FragRecipe, arg.ID)
	return err
}

const setDocumentHash = `-- name: SetDocumentHash :exec
UPDATE documents SET content_hash = ? WHERE path = ?
`

type SetDocumentHashParams struct {
	ContentHash string `db:"content_hash" derived:"documents.content_hash" json:"content_hash"`
	Path        string `db:"path" derived:"documents.path" json:"path"`
}

func (q *Queries) SetDocumentHash(ctx context.Context, arg SetDocumentHashParams) error {
	_, err := q.db.ExecContext(ctx, setDocumentHash, arg.ContentHash, arg.Path)
	return err
}

const setJobLane = `-- name: SetJobLane :exec
UPDATE ingest_jobs SET lane = ? WHERE id = ?
`

type SetJobLaneParams struct {
	Lane string `db:"lane" derived:"ingest_jobs.lane" json:"lane"`
	ID   int64  `db:"id" derived:"ingest_jobs.id" json:"id"`
}

func (q *Queries) SetJobLane(ctx context.Context, arg SetJobLaneParams) error {
	_, err := q.db.ExecContext(ctx, setJobLane, arg.Lane, arg.ID)
	return err
}

const setJobRunning = `-- name: SetJobRunning :exec
UPDATE ingest_jobs SET state='running', started_at=?, owner_pid=? WHERE id=?
`

type SetJobRunningParams struct {
	StartedAt int64 `db:"started_at" derived:"ingest_jobs.started_at" json:"started_at"`
	OwnerPid  int64 `db:"owner_pid" derived:"ingest_jobs.owner_pid" json:"owner_pid"`
	ID        int64 `db:"id" derived:"ingest_jobs.id" json:"id"`
}

func (q *Queries) SetJobRunning(ctx context.Context, arg SetJobRunningParams) error {
	_, err := q.db.ExecContext(ctx, setJobRunning, arg.StartedAt, arg.OwnerPid, arg.ID)
	return err
}

const upsertDocument = `-- name: UpsertDocument :one
INSERT INTO documents(path, title, added_at) VALUES(?, ?, ?)
ON CONFLICT(path) DO UPDATE SET title=excluded.title, added_at=excluded.added_at
RETURNING id
`

type UpsertDocumentParams struct {
	Path    string `db:"path" derived:"documents.path" json:"path"`
	Title   string `db:"title" derived:"documents.title" json:"title"`
	AddedAt int64  `db:"added_at" derived:"documents.added_at" json:"added_at"`
}

func (q *Queries) UpsertDocument(ctx context.Context, arg UpsertDocumentParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, upsertDocument, arg.Path, arg.Title, arg.AddedAt)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const upsertOcrPage = `-- name: UpsertOcrPage :exec
INSERT INTO ocr_pages(doc_id, page, engine, image_path) VALUES(?,?,?,?)
ON CONFLICT(doc_id, page) DO UPDATE SET engine=excluded.engine, image_path=excluded.image_path
`

type UpsertOcrPageParams struct {
	DocID     int64  `db:"doc_id" derived:"ocr_pages.doc_id" json:"doc_id"`
	Page      int64  `db:"page" derived:"ocr_pages.page" json:"page"`
	Engine    string `db:"engine" derived:"ocr_pages.engine" json:"engine"`
	ImagePath string `db:"image_path" derived:"ocr_pages.image_path" json:"image_path"`
}

// ===== ocr_pages =====
func (q *Queries) UpsertOcrPage(ctx context.Context, arg UpsertOcrPageParams) error {
	_, err := q.db.ExecContext(ctx, upsertOcrPage,
		arg.DocID,
		arg.Page,
		arg.Engine,
		arg.ImagePath,
	)
	return err
}

const upsertReading = `-- name: UpsertReading :exec
INSERT INTO readings(source_sha256, source_path, doc_path, method, level, produced_by, ruled_by, at)
VALUES(?,?,?,?,?,?,?,?)
ON CONFLICT(doc_path) DO UPDATE SET
  source_sha256=excluded.source_sha256, source_path=excluded.source_path,
  method=excluded.method, level=excluded.level, produced_by=excluded.produced_by,
  ruled_by=excluded.ruled_by, at=excluded.at
`

type UpsertReadingParams struct {
	SourceSha256 string `db:"source_sha256" derived:"readings.source_sha256" json:"source_sha256"`
	SourcePath   string `db:"source_path" derived:"readings.source_path" json:"source_path"`
	DocPath      string `db:"doc_path" derived:"readings.doc_path" json:"doc_path"`
	Method       string `db:"method" derived:"readings.method" json:"method"`
	Level        string `db:"level" derived:"readings.level" json:"level"`
	ProducedBy   string `db:"produced_by" derived:"readings.produced_by" json:"produced_by"`
	RuledBy      string `db:"ruled_by" derived:"readings.ruled_by" json:"ruled_by"`
	At           int64  `db:"at" derived:"readings.at" json:"at"`
}

// ===== readings =====
func (q *Queries) UpsertReading(ctx context.Context, arg UpsertReadingParams) error {
	_, err := q.db.ExecContext(ctx, upsertReading,
		arg.SourceSha256,
		arg.SourcePath,
		arg.DocPath,
		arg.Method,
		arg.Level,
		arg.ProducedBy,
		arg.RuledBy,
		arg.At,
	)
	return err
}
