// Code generated by sqlc-go-codegen-metaquery. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: query.sql

package db

import (
	"github.com/iodesystems/sqlc-go-codegen-metaquery/metaquery"
)

var _ = metaquery.Query{}

var MetaDeleteFragmentsByDoc = metaquery.Query{
	Name:    "DeleteFragmentsByDoc",
	Cmd:     ":exec",
	Source:  "query.sql",
	Dialect: metaquery.DialectSQLite,
	SQL:     `DELETE FROM fragments WHERE doc_id = ?`,
	Args: []metaquery.Arg{
		{Position: 1, Name: "doc_id", GoType: "int64", DBType: "INTEGER", NotNull: true},
	},
}

// WrapDeleteFragmentsByDoc returns a metaquery.Builder over MetaDeleteFragmentsByDoc, pre-bound with typed arguments.
func WrapDeleteFragmentsByDoc(docID int64) *metaquery.Builder {
	return metaquery.Wrap(&MetaDeleteFragmentsByDoc, docID)
}

var MetaEnqueueJob = metaquery.Query{
	Name:    "EnqueueJob",
	Cmd:     ":one",
	Source:  "query.sql",
	Dialect: metaquery.DialectSQLite,
	SQL:     `INSERT INTO ingest_jobs(url, title, state, enqueued_at) VALUES(?, ?, 'pending', ?) RETURNING id`,
	Columns: []metaquery.Column{
		{Name: "id", OriginalName: "id", GoType: "int64"},
	},
	Args: []metaquery.Arg{
		{Position: 1, Name: "url", GoType: "string", DBType: "TEXT", NotNull: true},
		{Position: 2, Name: "title", GoType: "string", DBType: "TEXT", NotNull: true},
		{Position: 3, Name: "enqueued_at", GoType: "int64", DBType: "INTEGER", NotNull: true},
	},
	Table: &metaquery.Table{Name: "ingest_jobs"},
}

// WrapEnqueueJob returns a metaquery.Builder over MetaEnqueueJob, pre-bound with typed arguments.
func WrapEnqueueJob(arg EnqueueJobParams) *metaquery.Builder {
	return metaquery.Wrap(&MetaEnqueueJob, arg.Url, arg.Title, arg.EnqueuedAt)
}

// EnqueueJobCols gives typed, name-safe access to EnqueueJob's output columns.
var EnqueueJobCols = struct {
	ID metaquery.IntCol
}{
	ID: metaquery.NewIntCol("id"),
}

var MetaGetDocumentByPath = metaquery.Query{
	Name:    "GetDocumentByPath",
	Cmd:     ":one",
	Source:  "query.sql",
	Dialect: metaquery.DialectSQLite,
	SQL:     `SELECT id, path, title, added_at FROM documents WHERE path = ?`,
	Columns: []metaquery.Column{
		{Name: "id", OriginalName: "id", GoType: "int64", DBType: "INTEGER", NotNull: true, Table: "documents"},
		{Name: "path", OriginalName: "path", GoType: "string", DBType: "TEXT", NotNull: true, Table: "documents"},
		{Name: "title", OriginalName: "title", GoType: "string", DBType: "TEXT", NotNull: true, Table: "documents"},
		{Name: "added_at", OriginalName: "added_at", GoType: "int64", DBType: "INTEGER", NotNull: true, Table: "documents"},
	},
	Args: []metaquery.Arg{
		{Position: 1, Name: "path", GoType: "string", DBType: "TEXT", NotNull: true},
	},
}

// WrapGetDocumentByPath returns a metaquery.Builder over MetaGetDocumentByPath, pre-bound with typed arguments.
func WrapGetDocumentByPath(path string) *metaquery.Builder {
	return metaquery.Wrap(&MetaGetDocumentByPath, path)
}

// GetDocumentByPathCols gives typed, name-safe access to GetDocumentByPath's output columns.
var GetDocumentByPathCols = struct {
	ID      metaquery.IntCol
	Path    metaquery.TextCol
	Title   metaquery.TextCol
	AddedAt metaquery.IntCol
}{
	ID:      metaquery.NewIntCol("id"),
	Path:    metaquery.NewTextCol("path"),
	Title:   metaquery.NewTextCol("title"),
	AddedAt: metaquery.NewIntCol("added_at"),
}

var MetaGetJob = metaquery.Query{
	Name:    "GetJob",
	Cmd:     ":one",
	Source:  "query.sql",
	Dialect: metaquery.DialectSQLite,
	SQL: `SELECT id, url, title, state, error, fragments, mode, enqueued_at, started_at, finished_at
FROM ingest_jobs WHERE id = ?`,
	Columns: []metaquery.Column{
		{Name: "id", OriginalName: "id", GoType: "int64", DBType: "INTEGER", NotNull: true, Table: "ingest_jobs"},
		{Name: "url", OriginalName: "url", GoType: "string", DBType: "TEXT", NotNull: true, Table: "ingest_jobs"},
		{Name: "title", OriginalName: "title", GoType: "string", DBType: "TEXT", NotNull: true, Table: "ingest_jobs"},
		{Name: "state", OriginalName: "state", GoType: "string", DBType: "TEXT", NotNull: true, Table: "ingest_jobs"},
		{Name: "error", OriginalName: "error", GoType: "string", DBType: "TEXT", NotNull: true, Table: "ingest_jobs"},
		{Name: "fragments", OriginalName: "fragments", GoType: "int64", DBType: "INTEGER", NotNull: true, Table: "ingest_jobs"},
		{Name: "mode", OriginalName: "mode", GoType: "string", DBType: "TEXT", NotNull: true, Table: "ingest_jobs"},
		{Name: "enqueued_at", OriginalName: "enqueued_at", GoType: "int64", DBType: "INTEGER", NotNull: true, Table: "ingest_jobs"},
		{Name: "started_at", OriginalName: "started_at", GoType: "int64", DBType: "INTEGER", NotNull: true, Table: "ingest_jobs"},
		{Name: "finished_at", OriginalName: "finished_at", GoType: "int64", DBType: "INTEGER", NotNull: true, Table: "ingest_jobs"},
	},
	Args: []metaquery.Arg{
		{Position: 1, Name: "id", GoType: "int64", DBType: "INTEGER", NotNull: true},
	},
}

// WrapGetJob returns a metaquery.Builder over MetaGetJob, pre-bound with typed arguments.
func WrapGetJob(id int64) *metaquery.Builder {
	return metaquery.Wrap(&MetaGetJob, id)
}

// GetJobCols gives typed, name-safe access to GetJob's output columns.
var GetJobCols = struct {
	ID         metaquery.IntCol
	Url        metaquery.TextCol
	Title      metaquery.TextCol
	State      metaquery.TextCol
	Error      metaquery.TextCol
	Fragments  metaquery.IntCol
	Mode       metaquery.TextCol
	EnqueuedAt metaquery.IntCol
	StartedAt  metaquery.IntCol
	FinishedAt metaquery.IntCol
}{
	ID:         metaquery.NewIntCol("id"),
	Url:        metaquery.NewTextCol("url"),
	Title:      metaquery.NewTextCol("title"),
	State:      metaquery.NewTextCol("state"),
	Error:      metaquery.NewTextCol("error"),
	Fragments:  metaquery.NewIntCol("fragments"),
	Mode:       metaquery.NewTextCol("mode"),
	EnqueuedAt: metaquery.NewIntCol("enqueued_at"),
	StartedAt:  metaquery.NewIntCol("started_at"),
	FinishedAt: metaquery.NewIntCol("finished_at"),
}

var MetaListDocuments = metaquery.Query{
	Name:    "ListDocuments",
	Cmd:     ":many",
	Source:  "query.sql",
	Dialect: metaquery.DialectSQLite,
	SQL:     `SELECT id, path, title, added_at FROM documents ORDER BY added_at DESC`,
	Columns: []metaquery.Column{
		{Name: "id", OriginalName: "id", GoType: "int64", DBType: "INTEGER", NotNull: true, Table: "documents"},
		{Name: "path", OriginalName: "path", GoType: "string", DBType: "TEXT", NotNull: true, Table: "documents"},
		{Name: "title", OriginalName: "title", GoType: "string", DBType: "TEXT", NotNull: true, Table: "documents"},
		{Name: "added_at", OriginalName: "added_at", GoType: "int64", DBType: "INTEGER", NotNull: true, Table: "documents"},
	},
}

// WARNING: ListDocuments ends in a top-level ORDER BY. Wrapping re-applies
// ordering at runtime, so .ApplyOrder(...) produces a doubled, nested sort
// that can defeat index use. Drop ORDER BY from the query and order via
// .ApplyOrder(...) instead. See benchmark/README.md.
// WrapListDocuments returns a metaquery.Builder over MetaListDocuments, pre-bound with typed arguments.
func WrapListDocuments() *metaquery.Builder {
	return metaquery.Wrap(&MetaListDocuments)
}

// ListDocumentsCols gives typed, name-safe access to ListDocuments's output columns.
var ListDocumentsCols = struct {
	ID      metaquery.IntCol
	Path    metaquery.TextCol
	Title   metaquery.TextCol
	AddedAt metaquery.IntCol
}{
	ID:      metaquery.NewIntCol("id"),
	Path:    metaquery.NewTextCol("path"),
	Title:   metaquery.NewTextCol("title"),
	AddedAt: metaquery.NewIntCol("added_at"),
}

var MetaListJobStages = metaquery.Query{
	Name:    "ListJobStages",
	Cmd:     ":many",
	Source:  "query.sql",
	Dialect: metaquery.DialectSQLite,
	SQL:     `SELECT seq, name, engine, state, detail, at FROM job_stages WHERE job_id = ? ORDER BY seq`,
	Columns: []metaquery.Column{
		{Name: "seq", OriginalName: "seq", GoType: "int64", DBType: "INTEGER", NotNull: true, Table: "job_stages"},
		{Name: "name", OriginalName: "name", GoType: "string", DBType: "TEXT", NotNull: true, Table: "job_stages"},
		{Name: "engine", OriginalName: "engine", GoType: "string", DBType: "TEXT", NotNull: true, Table: "job_stages"},
		{Name: "state", OriginalName: "state", GoType: "string", DBType: "TEXT", NotNull: true, Table: "job_stages"},
		{Name: "detail", OriginalName: "detail", GoType: "string", DBType: "TEXT", NotNull: true, Table: "job_stages"},
		{Name: "at", OriginalName: "at", GoType: "int64", DBType: "INTEGER", NotNull: true, Table: "job_stages"},
	},
	Args: []metaquery.Arg{
		{Position: 1, Name: "job_id", GoType: "int64", DBType: "INTEGER", NotNull: true},
	},
}

// WARNING: ListJobStages ends in a top-level ORDER BY. Wrapping re-applies
// ordering at runtime, so .ApplyOrder(...) produces a doubled, nested sort
// that can defeat index use. Drop ORDER BY from the query and order via
// .ApplyOrder(...) instead. See benchmark/README.md.
// WrapListJobStages returns a metaquery.Builder over MetaListJobStages, pre-bound with typed arguments.
func WrapListJobStages(jobID int64) *metaquery.Builder {
	return metaquery.Wrap(&MetaListJobStages, jobID)
}

// ListJobStagesCols gives typed, name-safe access to ListJobStages's output columns.
var ListJobStagesCols = struct {
	Seq    metaquery.IntCol
	Name   metaquery.TextCol
	Engine metaquery.TextCol
	State  metaquery.TextCol
	Detail metaquery.TextCol
	At     metaquery.IntCol
}{
	Seq:    metaquery.NewIntCol("seq"),
	Name:   metaquery.NewTextCol("name"),
	Engine: metaquery.NewTextCol("engine"),
	State:  metaquery.NewTextCol("state"),
	Detail: metaquery.NewTextCol("detail"),
	At:     metaquery.NewIntCol("at"),
}

var MetaListJobs = metaquery.Query{
	Name:    "ListJobs",
	Cmd:     ":many",
	Source:  "query.sql",
	Dialect: metaquery.DialectSQLite,
	SQL: `SELECT id, url, title, state, error, fragments, mode, enqueued_at, started_at, finished_at
FROM ingest_jobs ORDER BY id DESC LIMIT ?`,
	Columns: []metaquery.Column{
		{Name: "id", OriginalName: "id", GoType: "int64", DBType: "INTEGER", NotNull: true, Table: "ingest_jobs"},
		{Name: "url", OriginalName: "url", GoType: "string", DBType: "TEXT", NotNull: true, Table: "ingest_jobs"},
		{Name: "title", OriginalName: "title", GoType: "string", DBType: "TEXT", NotNull: true, Table: "ingest_jobs"},
		{Name: "state", OriginalName: "state", GoType: "string", DBType: "TEXT", NotNull: true, Table: "ingest_jobs"},
		{Name: "error", OriginalName: "error", GoType: "string", DBType: "TEXT", NotNull: true, Table: "ingest_jobs"},
		{Name: "fragments", OriginalName: "fragments", GoType: "int64", DBType: "INTEGER", NotNull: true, Table: "ingest_jobs"},
		{Name: "mode", OriginalName: "mode", GoType: "string", DBType: "TEXT", NotNull: true, Table: "ingest_jobs"},
		{Name: "enqueued_at", OriginalName: "enqueued_at", GoType: "int64", DBType: "INTEGER", NotNull: true, Table: "ingest_jobs"},
		{Name: "started_at", OriginalName: "started_at", GoType: "int64", DBType: "INTEGER", NotNull: true, Table: "ingest_jobs"},
		{Name: "finished_at", OriginalName: "finished_at", GoType: "int64", DBType: "INTEGER", NotNull: true, Table: "ingest_jobs"},
	},
	Args: []metaquery.Arg{
		{Position: 1, Name: "limit", GoType: "int64", DBType: "integer", NotNull: true},
	},
}

// WARNING: ListJobs ends in a top-level ORDER BY. Wrapping re-applies
// ordering at runtime, so .ApplyOrder(...) produces a doubled, nested sort
// that can defeat index use. Drop ORDER BY from the query and order via
// .ApplyOrder(...) instead. See benchmark/README.md.
// WrapListJobs returns a metaquery.Builder over MetaListJobs, pre-bound with typed arguments.
func WrapListJobs(limit int64) *metaquery.Builder {
	return metaquery.Wrap(&MetaListJobs, limit)
}

// ListJobsCols gives typed, name-safe access to ListJobs's output columns.
var ListJobsCols = struct {
	ID         metaquery.IntCol
	Url        metaquery.TextCol
	Title      metaquery.TextCol
	State      metaquery.TextCol
	Error      metaquery.TextCol
	Fragments  metaquery.IntCol
	Mode       metaquery.TextCol
	EnqueuedAt metaquery.IntCol
	StartedAt  metaquery.IntCol
	FinishedAt metaquery.IntCol
}{
	ID:         metaquery.NewIntCol("id"),
	Url:        metaquery.NewTextCol("url"),
	Title:      metaquery.NewTextCol("title"),
	State:      metaquery.NewTextCol("state"),
	Error:      metaquery.NewTextCol("error"),
	Fragments:  metaquery.NewIntCol("fragments"),
	Mode:       metaquery.NewTextCol("mode"),
	EnqueuedAt: metaquery.NewIntCol("enqueued_at"),
	StartedAt:  metaquery.NewIntCol("started_at"),
	FinishedAt: metaquery.NewIntCol("finished_at"),
}

var MetaListOcrPagesByDoc = metaquery.Query{
	Name:    "ListOcrPagesByDoc",
	Cmd:     ":many",
	Source:  "query.sql",
	Dialect: metaquery.DialectSQLite,
	SQL:     `SELECT page, engine, image_path FROM ocr_pages WHERE doc_id = ? ORDER BY page`,
	Columns: []metaquery.Column{
		{Name: "page", OriginalName: "page", GoType: "int64", DBType: "INTEGER", NotNull: true, Table: "ocr_pages"},
		{Name: "engine", OriginalName: "engine", GoType: "string", DBType: "TEXT", NotNull: true, Table: "ocr_pages"},
		{Name: "image_path", OriginalName: "image_path", GoType: "string", DBType: "TEXT", NotNull: true, Table: "ocr_pages"},
	},
	Args: []metaquery.Arg{
		{Position: 1, Name: "doc_id", GoType: "int64", DBType: "INTEGER", NotNull: true},
	},
}

// WARNING: ListOcrPagesByDoc ends in a top-level ORDER BY. Wrapping re-applies
// ordering at runtime, so .ApplyOrder(...) produces a doubled, nested sort
// that can defeat index use. Drop ORDER BY from the query and order via
// .ApplyOrder(...) instead. See benchmark/README.md.
// WrapListOcrPagesByDoc returns a metaquery.Builder over MetaListOcrPagesByDoc, pre-bound with typed arguments.
func WrapListOcrPagesByDoc(docID int64) *metaquery.Builder {
	return metaquery.Wrap(&MetaListOcrPagesByDoc, docID)
}

// ListOcrPagesByDocCols gives typed, name-safe access to ListOcrPagesByDoc's output columns.
var ListOcrPagesByDocCols = struct {
	Page      metaquery.IntCol
	Engine    metaquery.TextCol
	ImagePath metaquery.TextCol
}{
	Page:      metaquery.NewIntCol("page"),
	Engine:    metaquery.NewTextCol("engine"),
	ImagePath: metaquery.NewTextCol("image_path"),
}

var MetaUpsertDocument = metaquery.Query{
	Name:    "UpsertDocument",
	Cmd:     ":one",
	Source:  "query.sql",
	Dialect: metaquery.DialectSQLite,
	SQL: `INSERT INTO documents(path, title, added_at) VALUES(?, ?, ?)
ON CONFLICT(path) DO UPDATE SET title=excluded.title, added_at=excluded.added_at
RETURNING id`,
	Columns: []metaquery.Column{
		{Name: "id", OriginalName: "id", GoType: "int64"},
	},
	Args: []metaquery.Arg{
		{Position: 1, Name: "path", GoType: "string", DBType: "TEXT", NotNull: true},
		{Position: 2, Name: "title", GoType: "string", DBType: "TEXT", NotNull: true},
		{Position: 3, Name: "added_at", GoType: "int64", DBType: "INTEGER", NotNull: true},
	},
	Table: &metaquery.Table{Name: "documents"},
}

// WrapUpsertDocument returns a metaquery.Builder over MetaUpsertDocument, pre-bound with typed arguments.
func WrapUpsertDocument(arg UpsertDocumentParams) *metaquery.Builder {
	return metaquery.Wrap(&MetaUpsertDocument, arg.Path, arg.Title, arg.AddedAt)
}

// UpsertDocumentCols gives typed, name-safe access to UpsertDocument's output columns.
var UpsertDocumentCols = struct {
	ID metaquery.IntCol
}{
	ID: metaquery.NewIntCol("id"),
}
