// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: query.sql

package db

import (
	"context"
)

const deleteFragmentsByDoc = `-- name: DeleteFragmentsByDoc :exec
DELETE FROM fragments WHERE doc_id = ?
`

func (q *Queries) DeleteFragmentsByDoc(ctx context.Context, docID int64) error {
	_, err := q.db.ExecContext(ctx, deleteFragmentsByDoc, docID)
	return err
}

const enqueueJob = `-- name: EnqueueJob :one
INSERT INTO ingest_jobs(url, title, state, enqueued_at) VALUES(?, ?, 'pending', ?) RETURNING id
`

type EnqueueJobParams struct {
	Url        string `db:"url" derived:"ingest_jobs.url" json:"url"`
	Title      string `db:"title" derived:"ingest_jobs.title" json:"title"`
	EnqueuedAt int64  `db:"enqueued_at" derived:"ingest_jobs.enqueued_at" json:"enqueued_at"`
}

func (q *Queries) EnqueueJob(ctx context.Context, arg EnqueueJobParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, enqueueJob, arg.Url, arg.Title, arg.EnqueuedAt)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const getDocumentByPath = `-- name: GetDocumentByPath :one
SELECT id, path, title, added_at FROM documents WHERE path = ?
`

func (q *Queries) GetDocumentByPath(ctx context.Context, path string) (Document, error) {
	row := q.db.QueryRowContext(ctx, getDocumentByPath, path)
	var i Document
	err := row.Scan(
		&i.ID,
		&i.Path,
		&i.Title,
		&i.AddedAt,
	)
	return i, err
}

const getJob = `-- name: GetJob :one
SELECT id, url, title, state, error, fragments, mode, enqueued_at, started_at, finished_at
FROM ingest_jobs WHERE id = ?
`

func (q *Queries) GetJob(ctx context.Context, id int64) (IngestJob, error) {
	row := q.db.QueryRowContext(ctx, getJob, id)
	var i IngestJob
	err := row.Scan(
		&i.ID,
		&i.Url,
		&i.Title,
		&i.State,
		&i.Error,
		&i.Fragments,
		&i.Mode,
		&i.EnqueuedAt,
		&i.StartedAt,
		&i.FinishedAt,
	)
	return i, err
}

const listDocuments = `-- name: ListDocuments :many
SELECT id, path, title, added_at FROM documents ORDER BY added_at DESC
`

func (q *Queries) ListDocuments(ctx context.Context) ([]Document, error) {
	rows, err := q.db.QueryContext(ctx, listDocuments)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Document
	for rows.Next() {
		var i Document
		if err := rows.Scan(
			&i.ID,
			&i.Path,
			&i.Title,
			&i.AddedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listJobStages = `-- name: ListJobStages :many
SELECT seq, name, engine, state, detail, at FROM job_stages WHERE job_id = ? ORDER BY seq
`

type ListJobStagesRow struct {
	Seq    int64  `db:"seq" derived:"job_stages.seq" json:"seq"`
	Name   string `db:"name" derived:"job_stages.name" json:"name"`
	Engine string `db:"engine" derived:"job_stages.engine" json:"engine"`
	State  string `db:"state" derived:"job_stages.state" json:"state"`
	Detail string `db:"detail" derived:"job_stages.detail" json:"detail"`
	At     int64  `db:"at" derived:"job_stages.at" json:"at"`
}

func (q *Queries) ListJobStages(ctx context.Context, jobID int64) ([]ListJobStagesRow, error) {
	rows, err := q.db.QueryContext(ctx, listJobStages, jobID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListJobStagesRow
	for rows.Next() {
		var i ListJobStagesRow
		if err := rows.Scan(
			&i.Seq,
			&i.Name,
			&i.Engine,
			&i.State,
			&i.Detail,
			&i.At,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listJobs = `-- name: ListJobs :many
SELECT id, url, title, state, error, fragments, mode, enqueued_at, started_at, finished_at
FROM ingest_jobs ORDER BY id DESC LIMIT ?
`

func (q *Queries) ListJobs(ctx context.Context, limit int64) ([]IngestJob, error) {
	rows, err := q.db.QueryContext(ctx, listJobs, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []IngestJob
	for rows.Next() {
		var i IngestJob
		if err := rows.Scan(
			&i.ID,
			&i.Url,
			&i.Title,
			&i.State,
			&i.Error,
			&i.Fragments,
			&i.Mode,
			&i.EnqueuedAt,
			&i.StartedAt,
			&i.FinishedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listOcrPagesByDoc = `-- name: ListOcrPagesByDoc :many
SELECT page, engine, image_path FROM ocr_pages WHERE doc_id = ? ORDER BY page
`

type ListOcrPagesByDocRow struct {
	Page      int64  `db:"page" derived:"ocr_pages.page" json:"page"`
	Engine    string `db:"engine" derived:"ocr_pages.engine" json:"engine"`
	ImagePath string `db:"image_path" derived:"ocr_pages.image_path" json:"image_path"`
}

func (q *Queries) ListOcrPagesByDoc(ctx context.Context, docID int64) ([]ListOcrPagesByDocRow, error) {
	rows, err := q.db.QueryContext(ctx, listOcrPagesByDoc, docID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListOcrPagesByDocRow
	for rows.Next() {
		var i ListOcrPagesByDocRow
		if err := rows.Scan(&i.Page, &i.Engine, &i.ImagePath); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertDocument = `-- name: UpsertDocument :one
INSERT INTO documents(path, title, added_at) VALUES(?, ?, ?)
ON CONFLICT(path) DO UPDATE SET title=excluded.title, added_at=excluded.added_at
RETURNING id
`

type UpsertDocumentParams struct {
	Path    string `db:"path" derived:"documents.path" json:"path"`
	Title   string `db:"title" derived:"documents.title" json:"title"`
	AddedAt int64  `db:"added_at" derived:"documents.added_at" json:"added_at"`
}

func (q *Queries) UpsertDocument(ctx context.Context, arg UpsertDocumentParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, upsertDocument, arg.Path, arg.Title, arg.AddedAt)
	var id int64
	err := row.Scan(&id)
	return id, err
}
